// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import type { ThreadMessageDtoMessageOneOf1 } from '../../../autogenerated';
import type { SocketEventHandler } from '../../../services/WebSocketService';
import { webSocketService } from '../../../services/WebSocketService';
import type { AgentMessageNotification } from '../../../services/WebSocketTypes';
import { NotificationScope } from '../../../services/WebSocketTypes';
import type { LoadedFixture, ProgressCallback } from './ws-replay.types';
import { WSEventPlayer } from './WSEventPlayer';

// Build a typed agent.message notification for use in fixtures.
// AgentMessageNotification.data is ThreadMessageDto which requires:
// id, threadId, nodeId, externalThreadId, createdAt, updatedAt, message.
function makeAgentMessage(
  id: string,
  content: string,
  threadId: string,
  graphId: string,
): AgentMessageNotification {
  const message: ThreadMessageDtoMessageOneOf1 = {
    role: 'ai',
    content,
  };
  return {
    type: 'agent.message',
    graphId,
    ownerId: 'owner-1',
    nodeId: 'supervisor',
    threadId,
    internalThreadId: threadId,
    scope: [NotificationScope.Graph],
    data: {
      id,
      threadId,
      nodeId: 'supervisor',
      externalThreadId: threadId,
      createdAt: '2026-04-24T00:00:00Z',
      updatedAt: '2026-04-24T00:00:00Z',
      message,
    },
  };
}

// 3-event fixture used by most tests (delays: 100, 200, 300 ms).
const testFixture: LoadedFixture = {
  name: 'test',
  description: 'test fixture',
  threadId: 'thread-1',
  graphId: 'graph-1',
  events: [
    { delayMs: 100, event: makeAgentMessage('m1', 'a', 'thread-1', 'graph-1') },
    { delayMs: 200, event: makeAgentMessage('m2', 'b', 'thread-1', 'graph-1') },
    { delayMs: 300, event: makeAgentMessage('m3', 'c', 'thread-1', 'graph-1') },
  ],
};

describe('WSEventPlayer', () => {
  let spy: ReturnType<typeof vi.fn<SocketEventHandler>>;
  let progressSpy: ReturnType<typeof vi.fn<ProgressCallback>>;

  beforeEach(() => {
    vi.useFakeTimers();
    spy = vi.fn<SocketEventHandler>();
    progressSpy = vi.fn<ProgressCallback>();
    webSocketService.on('agent.message', spy);
  });

  afterEach(() => {
    webSocketService.off('agent.message', spy);
    vi.useRealTimers();
  });

  it('play() emits events at delayMs cadence', () => {
    const player = new WSEventPlayer(testFixture, progressSpy);
    player.play();

    // Advance to first event's delay and flush the inner setTimeout(fn, 0).
    vi.advanceTimersByTime(100 + 1);
    expect(spy).toHaveBeenCalledTimes(1);

    // Advance to second event's delay (200ms more) and flush.
    vi.advanceTimersByTime(200 + 1);
    expect(spy).toHaveBeenCalledTimes(2);

    // Advance to third event's delay (300ms more) and flush.
    vi.advanceTimersByTime(300 + 1);
    expect(spy).toHaveBeenCalledTimes(3);

    player.dispose();
  });

  it('pause() halts emission', () => {
    const player = new WSEventPlayer(testFixture, progressSpy);
    player.play();

    // Let the first event fire.
    vi.advanceTimersByTime(100 + 1);
    expect(spy).toHaveBeenCalledTimes(1);

    player.pause();

    // Advance well past the second and third events' remaining delays.
    vi.advanceTimersByTime(600 + 1);
    expect(spy).toHaveBeenCalledTimes(1);

    player.dispose();
  });

  it('step() advances exactly one event per call', () => {
    const player = new WSEventPlayer(testFixture, progressSpy);

    // step() calls emitCurrentEvent() which calls emitToHandlers(), which
    // wraps handler invocations in setTimeout(fn, 0). Flush after each step.
    player.step();
    vi.advanceTimersByTime(1);
    expect(spy).toHaveBeenCalledTimes(1);

    player.step();
    vi.advanceTimersByTime(1);
    expect(spy).toHaveBeenCalledTimes(2);

    player.dispose();
  });

  it('reset() restarts from index 0', () => {
    const player = new WSEventPlayer(testFixture, progressSpy);
    player.play();

    // Fire first two events.
    vi.advanceTimersByTime(100 + 1);
    vi.advanceTimersByTime(200 + 1);
    expect(spy).toHaveBeenCalledTimes(2);

    // Reset stops playback and rewinds to index 0.
    player.reset();
    player.play();

    // Fire all three events in the second run.
    vi.advanceTimersByTime(100 + 1);
    vi.advanceTimersByTime(200 + 1);
    vi.advanceTimersByTime(300 + 1);

    // 2 from first run + 3 from second run.
    expect(spy).toHaveBeenCalledTimes(5);

    // Confirm the replay restarted at m1.
    const firstReplayCall = spy.mock.calls[2][0] as AgentMessageNotification;
    expect(firstReplayCall.data.id).toBe('m1');

    player.dispose();
  });

  it('setSpeed(4) scales delays correctly', () => {
    const speedFixture: LoadedFixture = {
      name: 'speed-test',
      description: 'speed fixture',
      threadId: 'thread-2',
      graphId: 'graph-2',
      events: [
        {
          delayMs: 1000,
          event: makeAgentMessage('ms1', 'fast', 'thread-2', 'graph-2'),
        },
      ],
    };

    const speedSpy = vi.fn<SocketEventHandler>();
    webSocketService.on('agent.message', speedSpy);

    const player = new WSEventPlayer(speedFixture, progressSpy);
    player.setSpeed(4);
    player.play();

    // Effective delay = 1000 / 4 = 250 ms.
    // Advancing 249 ms must not yet fire.
    vi.advanceTimersByTime(249);
    expect(speedSpy).toHaveBeenCalledTimes(0);

    // Advancing the remaining 1 ms reaches the 250ms threshold;
    // flush the inner setTimeout(fn, 0) with one more ms.
    vi.advanceTimersByTime(1 + 1);
    expect(speedSpy).toHaveBeenCalledTimes(1);

    webSocketService.off('agent.message', speedSpy);
    player.dispose();
  });

  it('onProgress fires on every emission', () => {
    const player = new WSEventPlayer(testFixture, progressSpy);
    player.play();

    // Complete the full fixture.
    vi.advanceTimersByTime(100 + 1);
    vi.advanceTimersByTime(200 + 1);
    vi.advanceTimersByTime(300 + 1);

    // Progress is called at least once per emitted event.
    expect(progressSpy.mock.calls.length).toBeGreaterThanOrEqual(
      testFixture.events.length,
    );

    player.dispose();
  });

  it('dispose() clears pending timers and suppresses future emissions', () => {
    const player = new WSEventPlayer(testFixture, progressSpy);
    player.play();

    // Advance halfway to the first event (50 ms of 100 ms delay) — no fire yet.
    vi.advanceTimersByTime(50);
    expect(spy).toHaveBeenCalledTimes(0);

    player.dispose();

    // Advance past the original first-event deadline and flush any stray timers.
    vi.advanceTimersByTime(60 + 1);
    expect(spy).toHaveBeenCalledTimes(0);
  });
});
