#!/bin/sh
# Zitadel initialization script
# Creates: geniro project, geniro OIDC app (public, PKCE), demo users
# IDEMPOTENT: safe to re-run — handles 409 Conflict silently
#
# Auth: reads a PAT generated by Zitadel's start-from-init (machine user)
# from the shared volume at /zitadel-init/pat.txt

set -e

ZITADEL_URL="http://zitadel:8080"
# Zitadel resolves instances by domain from the Host header.
# Inside Docker, we connect to "zitadel:8080" but the external domain is "localhost".
ZITADEL_HOST="localhost"

# --- Install jq for safe JSON construction ---
apk add --no-cache jq > /dev/null 2>&1

# --- Helper: curl wrapper that always sends the correct Host header ---
zcurl() {
  curl -H "Host: ${ZITADEL_HOST}" "$@"
}

# --- Wait for Zitadel to be ready ---
echo "[init] Waiting for Zitadel API..."
for i in $(seq 1 30); do
  if zcurl -sf "${ZITADEL_URL}/debug/healthz" > /dev/null 2>&1; then
    echo "[init] Zitadel is ready."
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "[init] ERROR: Zitadel did not become ready in time."
    exit 1
  fi
  echo "[init] Waiting... attempt $i"
  sleep 5
done

# --- Read PAT from shared volume ---
PAT_FILE="/zitadel-init/pat.txt"
echo "[init] Reading PAT from ${PAT_FILE}..."

for i in $(seq 1 12); do
  if [ -f "${PAT_FILE}" ] && [ -s "${PAT_FILE}" ]; then
    PAT_TOKEN=$(cat "${PAT_FILE}" | tr -d '[:space:]')
    break
  fi
  if [ "$i" -eq 12 ]; then
    echo "[init] ERROR: PAT file not found or empty after 60s."
    echo "[init] Ensure ZITADEL_FIRSTINSTANCE_PATPATH is set in docker-compose.yml"
    exit 1
  fi
  echo "[init] PAT file not ready yet... attempt $i"
  sleep 5
done

AUTH_HEADER="Authorization: Bearer ${PAT_TOKEN}"
echo "[init] PAT loaded."

# --- Verify management API access ---
echo "[init] Verifying management API access..."
ORG_RESPONSE=$(zcurl -s -X GET "${ZITADEL_URL}/management/v1/orgs/me" \
  -H "${AUTH_HEADER}" \
  -H "Content-Type: application/json" 2>&1)

if echo "${ORG_RESPONSE}" | grep -q '"org"'; then
  echo "[init] Management API accessible."
else
  echo "[init] ERROR: Cannot access management API."
  echo "[init] Response: ${ORG_RESPONSE}"
  exit 1
fi

# --- Create project ---
echo "[init] Creating 'geniro' project..."
PROJECT_BODY=$(jq -n '{
  "name": "geniro",
  "projectRoleAssertion": false,
  "projectRoleCheck": false,
  "hasProjectCheck": false
}')
PROJECT_RESPONSE=$(zcurl -s -X POST "${ZITADEL_URL}/management/v1/projects" \
  -H "${AUTH_HEADER}" \
  -H "Content-Type: application/json" \
  -d "${PROJECT_BODY}")

PROJECT_ID=$(echo "${PROJECT_RESPONSE}" | jq -r '.id // empty')

if [ -z "${PROJECT_ID}" ]; then
  if echo "${PROJECT_RESPONSE}" | grep -q '"alreadyExists"\|"code":6'; then
    echo "[init] Project 'geniro' already exists, looking up ID..."
  else
    echo "[init] Project creation returned no ID, searching for existing..."
  fi

  PROJECTS_SEARCH_BODY=$(jq -n '{"queries": [{"nameQuery": {"name": "geniro", "method": "TEXT_QUERY_METHOD_EQUALS"}}]}')
  PROJECTS_LIST=$(zcurl -sf -X POST "${ZITADEL_URL}/management/v1/projects/_search" \
    -H "${AUTH_HEADER}" \
    -H "Content-Type: application/json" \
    -d "${PROJECTS_SEARCH_BODY}")

  PROJECT_ID=$(echo "${PROJECTS_LIST}" | jq -r '.result[0].id // empty')
fi

if [ -z "${PROJECT_ID}" ]; then
  echo "[init] ERROR: Could not create or find 'geniro' project."
  echo "[init] Response: ${PROJECT_RESPONSE}"
  exit 1
fi
echo "[init] Project ID: ${PROJECT_ID}"

# --- Create OIDC app (public client, PKCE, auth code flow) ---
echo "[init] Creating 'geniro' OIDC app..."
APP_BODY=$(jq -n '{
  "name": "geniro",
  "redirectUris": [
    "http://localhost:5174/callback",
    "http://localhost:5174/silent-renew",
    "http://localhost:4173/callback",
    "http://localhost:4173/silent-renew"
  ],
  "postLogoutRedirectUris": [
    "http://localhost:5174",
    "http://localhost:4173"
  ],
  "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
  "grantTypes": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
  "appType": "OIDC_APP_TYPE_USER_AGENT",
  "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",
  "devMode": true,
  "accessTokenType": "OIDC_TOKEN_TYPE_JWT",
  "idTokenRoleAssertion": true,
  "idTokenUserinfoAssertion": true
}')
APP_RESPONSE=$(zcurl -s -X POST "${ZITADEL_URL}/management/v1/projects/${PROJECT_ID}/apps/oidc" \
  -H "${AUTH_HEADER}" \
  -H "Content-Type: application/json" \
  -d "${APP_BODY}")

APP_ID=$(echo "${APP_RESPONSE}" | jq -r '.appId // empty')
CLIENT_ID=$(echo "${APP_RESPONSE}" | jq -r '.clientId // empty')

if [ -z "${APP_ID}" ]; then
  if echo "${APP_RESPONSE}" | grep -q '"alreadyExists"\|"code":6'; then
    echo "[init] OIDC app 'geniro' already exists, looking up client ID..."
  else
    echo "[init] OIDC app creation returned unexpected response (may already exist)."
    echo "[init] Response: ${APP_RESPONSE}"
  fi

  # Look up existing app to get the client ID
  APPS_RESPONSE=$(zcurl -sf -X POST "${ZITADEL_URL}/management/v1/projects/${PROJECT_ID}/apps/_search" \
    -H "${AUTH_HEADER}" \
    -H "Content-Type: application/json" \
    -d '{}')
  CLIENT_ID=$(echo "${APPS_RESPONSE}" | jq -r '.result[] | select(.name == "geniro") | .oidcConfig.clientId // empty')
else
  echo "[init] OIDC App ID: ${APP_ID}"
fi

# Write client ID to host-accessible volume so the backend can read it
if [ -n "${CLIENT_ID}" ]; then
  echo "[init] Client ID: ${CLIENT_ID}"
  echo -n "${CLIENT_ID}" > /zitadel-output/client-id.txt
  echo "[init] Client ID written to .docker/zitadel/data/client-id.txt"
else
  echo "[init] WARNING: Could not determine client ID."
fi

# --- Configure branding / label policy ---
echo "[init] Configuring Geniro branding..."

LABEL_BODY=$(jq -n '{
  "primaryColor": "#3B8DD4",
  "primaryColorDark": "#5BA3E0",
  "backgroundColor": "#f5f7fa",
  "backgroundColorDark": "#1a1a2e",
  "fontColor": "#111827",
  "fontColorDark": "#e5e7eb",
  "warnColor": "#ff4d4f",
  "warnColorDark": "#ff7875",
  "hideLoginNameSuffix": true,
  "disableWatermark": true,
  "themeMode": "THEME_MODE_AUTO"
}')

# Try to create label policy; if exists, update it
LABEL_RESPONSE=$(zcurl -s -X POST "${ZITADEL_URL}/management/v1/policies/label" \
  -H "${AUTH_HEADER}" \
  -H "Content-Type: application/json" \
  -d "${LABEL_BODY}")

if echo "${LABEL_RESPONSE}" | grep -q '"alreadyExists"\|"code":6'; then
  echo "[init] Label policy exists, updating..."
  zcurl -s -X PUT "${ZITADEL_URL}/management/v1/policies/label" \
    -H "${AUTH_HEADER}" \
    -H "Content-Type: application/json" \
    -d "${LABEL_BODY}" > /dev/null
fi

# Download logo from web app and upload to Zitadel
LOGO_URL="http://host.docker.internal:5174/logo.png"
LOGO_TMP="/tmp/logo.png"
if curl -sf -o "${LOGO_TMP}" "${LOGO_URL}" 2>/dev/null || curl -sf -o "${LOGO_TMP}" "http://localhost:5174/logo.png" 2>/dev/null; then
  echo "[init] Uploading logo..."
  zcurl -s -X POST "${ZITADEL_URL}/management/v1/policies/label/logo" \
    -H "${AUTH_HEADER}" \
    -F "file=@${LOGO_TMP}" > /dev/null 2>&1 || true
  zcurl -s -X POST "${ZITADEL_URL}/management/v1/policies/label/logo_dark" \
    -H "${AUTH_HEADER}" \
    -F "file=@${LOGO_TMP}" > /dev/null 2>&1 || true
  rm -f "${LOGO_TMP}"
else
  echo "[init] Warning: Could not download logo from web app, skipping logo upload"
fi

# Activate the label policy
echo "[init] Activating label policy..."
zcurl -s -X POST "${ZITADEL_URL}/management/v1/policies/label/_activate" \
  -H "${AUTH_HEADER}" \
  -H "Content-Type: application/json" \
  -d '{}' > /dev/null

echo "[init] Branding configured."

# --- Helper: create human user (idempotent) ---
create_user() {
  local username="$1"
  local password="$2"
  local given_name="$3"
  local family_name="$4"
  local email="$5"
  local display_name="${given_name} ${family_name}"

  echo "[init] Creating user '${username}'..."
  USER_BODY=$(jq -n \
    --arg u "${username}" \
    --arg p "${password}" \
    --arg gn "${given_name}" \
    --arg fn "${family_name}" \
    --arg dn "${display_name}" \
    --arg em "${email}" \
    '{
      "userName": $u,
      "profile": {
        "firstName": $gn,
        "lastName": $fn,
        "displayName": $dn
      },
      "email": {
        "email": $em,
        "isEmailVerified": true
      },
      "password": $p
    }')
  USER_RESPONSE=$(zcurl -s -X POST "${ZITADEL_URL}/management/v1/users/human/_import" \
    -H "${AUTH_HEADER}" \
    -H "Content-Type: application/json" \
    -d "${USER_BODY}")

  USER_ID=$(echo "${USER_RESPONSE}" | jq -r '.userId // empty')
  if [ -n "${USER_ID}" ]; then
    echo "[init] User '${username}' created (ID: ${USER_ID})."
  elif echo "${USER_RESPONSE}" | grep -q '"alreadyExists"\|"code":6'; then
    echo "[init] User '${username}' already exists."
  else
    echo "[init] WARN: User '${username}' creation returned unexpected response."
    echo "[init] Response: ${USER_RESPONSE}"
  fi
}

# --- Create demo users ---
create_user "s.razumru" 'DevPassword123!' "Sergei" "Razumovskij" "s.razumru@geniro.localhost"
create_user "claude-test" "ClaudeTest-2026" "Claude" "Test" "claude-test@geniro.localhost"

echo "[init] Zitadel initialization complete."
