/**
 * Unit tests for the cost-limit banner logic in ThreadMessagesView.
 *
 * The banner is rendered when stopReason === 'cost_limit' AND the thread is
 * stopped. These tests validate the condition and the USD formatting helper
 * used in the banner. Full component rendering is not covered here because the
 * vitest environment is 'node' (no DOM), matching the project's existing test
 * pattern.
 *
 * shouldShowCostLimitBanner is imported directly from ThreadMessagesView so
 * these tests exercise the real production code — removing or changing the
 * 'cost_limit' check in that file will cause these tests to fail.
 */

import { describe, expect, it } from 'vitest';

import type { ThreadMessageDto } from '@/autogenerated/api';

import { formatUsd } from '../../chats/utils/chatsPageUtils';
import type { PreparedMessage } from './threadMessages/threadMessagesTypes';
import {
  computeCollapsedHiddenCount,
  computeSubagentRollup,
  computeVisibleCollapsibleItems,
  shouldShowCostLimitBanner,
} from './ThreadMessagesView';

describe('cost-limit banner visibility', () => {
  it('shows banner when stopReason is "cost_limit" and thread is stopped', () => {
    expect(shouldShowCostLimitBanner('cost_limit', true)).toBe(true);
  });

  it('does not show banner when stopReason is "cost_limit" but thread is not stopped', () => {
    expect(shouldShowCostLimitBanner('cost_limit', false)).toBe(false);
  });

  it('does not show banner when stopReason is undefined (thread stopped)', () => {
    expect(shouldShowCostLimitBanner(undefined, true)).toBe(false);
  });

  it('does not show banner when stopReason is null (thread stopped)', () => {
    expect(shouldShowCostLimitBanner(null, true)).toBe(false);
  });

  it('does not show banner when stopReason is an empty string (thread stopped)', () => {
    expect(shouldShowCostLimitBanner('', true)).toBe(false);
  });

  it('does not show banner when stopReason is "user_stop" (thread stopped)', () => {
    expect(shouldShowCostLimitBanner('user_stop', true)).toBe(false);
  });

  it('does not show banner when stopReason is "error" (thread stopped)', () => {
    expect(shouldShowCostLimitBanner('error', true)).toBe(false);
  });

  it('condition is case-sensitive — does not match "Cost_Limit" (thread stopped)', () => {
    expect(shouldShowCostLimitBanner('Cost_Limit', true)).toBe(false);
  });

  it('stop-flag alone does not trigger banner when stopReason is unrelated', () => {
    expect(shouldShowCostLimitBanner('user_stop', true)).toBe(false);
  });
});

// ─── Banner cost formatting ───────────────────────────────────────────────────

describe('cost-limit banner USD formatting', () => {
  it('formats a whole-dollar amount correctly', () => {
    expect(formatUsd(1)).toBe('$1.00');
  });

  it('formats a fractional amount correctly', () => {
    expect(formatUsd(0.5)).toBe('$0.50');
  });

  it('formats zero correctly', () => {
    expect(formatUsd(0)).toBe('$0.00');
  });

  it('returns a sub-cent placeholder for very small amounts', () => {
    expect(formatUsd(0.001)).toBe('<$0.01');
  });

  it('returns a dash placeholder for null stopCostUsd', () => {
    expect(formatUsd(null)).toBe('$\u2014');
  });

  it('returns a dash placeholder for undefined stopCostUsd', () => {
    expect(formatUsd(undefined)).toBe('$\u2014');
  });
});

// \u2500\u2500\u2500 Collapsible messages helpers \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

/**
 * Factory helpers for creating typed PreparedMessage items without inline `any`.
 * Using `as unknown as ThreadMessageDto` for the shared fake message is acceptable
 * because ThreadMessageDto has many required fields, and the helpers under test
 * only switch on `m.type` \u2014 they never read message content.
 */
const fakeMessage = {} as unknown as ThreadMessageDto;

function makeChat(id: string): Extract<PreparedMessage, { type: 'chat' }> {
  return { type: 'chat', id, message: fakeMessage };
}

function makeReasoning(
  id: string,
): Extract<PreparedMessage, { type: 'reasoning' }> {
  return { type: 'reasoning', id, message: fakeMessage };
}

function makeSubagent(
  id: string,
): Extract<PreparedMessage, { type: 'subagent' }> {
  return {
    type: 'subagent',
    id,
    toolCallId: id,
    innerMessages: [],
    status: 'executed',
  };
}

function makeCommunication(
  id: string,
): Extract<PreparedMessage, { type: 'communication' }> {
  return {
    type: 'communication',
    id,
    toolCallId: id,
    innerMessages: [],
    status: 'executed',
  };
}

function makeTool(id: string): Extract<PreparedMessage, { type: 'tool' }> {
  return {
    type: 'tool',
    id,
    name: 'noop',
    status: 'executed',
  };
}

function makeSystem(id: string): Extract<PreparedMessage, { type: 'system' }> {
  return { type: 'system', id, message: fakeMessage };
}

function makeSubagentWithPrice(
  id: string,
  price: number,
): Extract<PreparedMessage, { type: 'subagent' }> {
  return {
    type: 'subagent',
    id,
    toolCallId: id,
    innerMessages: [],
    status: 'executed',
    statistics: {
      usage: { totalPrice: price },
    },
  };
}

function makeSubagentNoPrice(
  id: string,
): Extract<PreparedMessage, { type: 'subagent' }> {
  return {
    type: 'subagent',
    id,
    toolCallId: id,
    innerMessages: [],
    status: 'executed',
  };
}

describe('computeVisibleCollapsibleItems', () => {
  it('returns empty list for empty items', () => {
    expect(computeVisibleCollapsibleItems([], 3)).toEqual([]);
  });

  it('returns all items when count equals limit', () => {
    const items = [makeChat('1'), makeChat('2'), makeChat('3')];
    expect(computeVisibleCollapsibleItems(items, 3)).toEqual(items);
  });

  it('returns last 3 chat items when 5 chats exceed limit of 3', () => {
    const items = [
      makeChat('1'),
      makeChat('2'),
      makeChat('3'),
      makeChat('4'),
      makeChat('5'),
    ];
    const result = computeVisibleCollapsibleItems(items, 3);
    expect(result).toEqual([makeChat('3'), makeChat('4'), makeChat('5')]);
    expect(result).toHaveLength(3);
  });

  it('returns all subagents plus last 3 chats when 11 chats + 3 subagents at end', () => {
    const items = [
      makeChat('c1'),
      makeChat('c2'),
      makeChat('c3'),
      makeChat('c4'),
      makeChat('c5'),
      makeChat('c6'),
      makeChat('c7'),
      makeChat('c8'),
      makeChat('c9'),
      makeChat('c10'),
      makeChat('c11'),
      makeSubagent('s1'),
      makeSubagent('s2'),
      makeSubagent('s3'),
    ];
    const result = computeVisibleCollapsibleItems(items, 3);
    expect(result).toEqual([
      makeChat('c9'),
      makeChat('c10'),
      makeChat('c11'),
      makeSubagent('s1'),
      makeSubagent('s2'),
      makeSubagent('s3'),
    ]);
    expect(result).toHaveLength(6);
  });

  it('pins ALL subagent/communication blocks regardless of position, plus last 3 narrative items', () => {
    const items = [
      makeSubagent('s1'),
      makeChat('c1'),
      makeChat('c2'),
      makeChat('c3'),
      makeChat('c4'),
      makeSubagent('s2'),
      makeChat('c5'),
      makeChat('c6'),
      makeChat('c7'),
      makeChat('c8'),
      makeSubagent('s3'),
      makeChat('c9'),
    ];
    const result = computeVisibleCollapsibleItems(items, 3);
    expect(result).toEqual([
      makeSubagent('s1'),
      makeSubagent('s2'),
      makeChat('c7'),
      makeChat('c8'),
      makeSubagent('s3'),
      makeChat('c9'),
    ]);
    expect(result.filter((m) => m.type === 'subagent')).toHaveLength(3);
    expect(result.filter((m) => m.type === 'chat')).toHaveLength(3);
  });

  it('returns only subagent/communication items when no narrative items exist', () => {
    const items = [
      makeSubagent('s1'),
      makeCommunication('c1'),
      makeSubagent('s2'),
    ];
    const result = computeVisibleCollapsibleItems(items, 3);
    expect(result).toEqual(items);
  });

  it('reasoning items do not consume the budget', () => {
    const items = [
      makeReasoning('r1'),
      makeReasoning('r2'),
      makeReasoning('r3'),
      makeReasoning('r4'),
      makeReasoning('r5'),
      makeChat('c1'),
      makeChat('c2'),
      makeChat('c3'),
    ];
    const result = computeVisibleCollapsibleItems(items, 3);
    expect(result).toEqual(items);
    expect(result).toHaveLength(8);
  });

  it('communication blocks are pinned like subagents', () => {
    const items = [
      makeChat('c1'),
      makeChat('c2'),
      makeChat('c3'),
      makeChat('c4'),
      makeChat('c5'),
      makeSubagent('s1'),
      makeCommunication('comm1'),
    ];
    const result = computeVisibleCollapsibleItems(items, 3);
    expect(result).toEqual([
      makeChat('c3'),
      makeChat('c4'),
      makeChat('c5'),
      makeSubagent('s1'),
      makeCommunication('comm1'),
    ]);
    expect(result.filter((m) => m.type === 'subagent')).toHaveLength(1);
    expect(result.filter((m) => m.type === 'communication')).toHaveLength(1);
  });
});

describe('computeCollapsedHiddenCount', () => {
  it('returns 0 for empty list', () => {
    expect(computeCollapsedHiddenCount([], 3)).toBe(0);
  });

  it('returns 0 when narrative count equals limit', () => {
    const items = [makeChat('1'), makeChat('2'), makeChat('3')];
    expect(computeCollapsedHiddenCount(items, 3)).toBe(0);
  });

  it('returns 2 when 5 chats exceed limit of 3', () => {
    const items = [
      makeChat('1'),
      makeChat('2'),
      makeChat('3'),
      makeChat('4'),
      makeChat('5'),
    ];
    expect(computeCollapsedHiddenCount(items, 3)).toBe(2);
  });

  it('returns 8 when 11 chats + 3 subagents, limit 3', () => {
    const items = [
      makeChat('c1'),
      makeChat('c2'),
      makeChat('c3'),
      makeChat('c4'),
      makeChat('c5'),
      makeChat('c6'),
      makeChat('c7'),
      makeChat('c8'),
      makeChat('c9'),
      makeChat('c10'),
      makeChat('c11'),
      makeSubagent('s1'),
      makeSubagent('s2'),
      makeSubagent('s3'),
    ];
    expect(computeCollapsedHiddenCount(items, 3)).toBe(8);
  });

  it('returns 0 when only subagents/communications exist', () => {
    const items = [
      makeSubagent('s1'),
      makeCommunication('c1'),
      makeSubagent('s2'),
    ];
    expect(computeCollapsedHiddenCount(items, 3)).toBe(0);
  });

  it('reasoning items do not affect the count', () => {
    const items = [
      makeReasoning('r1'),
      makeReasoning('r2'),
      makeChat('c1'),
      makeChat('c2'),
      makeReasoning('r3'),
      makeChat('c3'),
      makeReasoning('r4'),
      makeChat('c4'),
      makeChat('c5'),
    ];
    expect(computeCollapsedHiddenCount(items, 3)).toBe(2);
  });

  it('tool and system items count as narrative', () => {
    const items = [
      makeChat('c1'),
      makeTool('t1'),
      makeSystem('sys1'),
      makeChat('c2'),
      makeTool('t2'),
    ];
    expect(computeCollapsedHiddenCount(items, 3)).toBe(2);
  });

  it('returns 0 when limit is very high', () => {
    const items = [makeChat('1'), makeChat('2'), makeChat('3')];
    expect(computeCollapsedHiddenCount(items, 100)).toBe(0);
  });
});

// ─── computeSubagentRollup ────────────────────────────────────────────────────

describe('computeSubagentRollup', () => {
  it('returns { count: 0, cost: undefined } for an empty array', () => {
    expect(computeSubagentRollup([])).toEqual({ count: 0, cost: undefined });
  });

  it('returns count 1 and cost from a single subagent with price', () => {
    const items: PreparedMessage[] = [makeSubagentWithPrice('s1', 0.045)];
    const result = computeSubagentRollup(items);
    expect(result.count).toBe(1);
    expect(result.cost).toBeCloseTo(0.045, 9);
  });

  it('returns count 3 and summed cost for 3 subagents (all priced, done)', () => {
    // Test matrix: "All calls priced, done"
    const items: PreparedMessage[] = [
      makeSubagentWithPrice('s1', 0.045),
      makeSubagentWithPrice('s2', 0.08),
      makeSubagentWithPrice('s3', 0.108),
    ];
    const result = computeSubagentRollup(items);
    expect(result.count).toBe(3);
    // 0.045 + 0.080 + 0.108 = 0.233 (floating point: use tolerance)
    expect(result.cost).toBeCloseTo(0.233, 9);
  });

  it('counts only subagent-type items in a mixed array', () => {
    const items: PreparedMessage[] = [
      makeChat('c1'),
      makeSubagentWithPrice('s1', 0.045),
      makeTool('t1'),
      makeSubagentWithPrice('s2', 0.08),
      makeCommunication('comm1'),
      makeSubagentWithPrice('s3', 0.108),
      makeReasoning('r1'),
    ];
    const result = computeSubagentRollup(items);
    expect(result.count).toBe(3);
    expect(result.cost).toBeCloseTo(0.045 + 0.08 + 0.108, 9);
  });

  it('increments count but keeps cost undefined when subagent has no price data', () => {
    // Test matrix: "Subagent without cost data"
    const items: PreparedMessage[] = [makeSubagentNoPrice('s1')];
    const result = computeSubagentRollup(items);
    expect(result.count).toBe(1);
    expect(result.cost).toBeUndefined();
  });

  it('sums only defined costs when some subagents have cost and some do not', () => {
    const items: PreparedMessage[] = [
      makeSubagentWithPrice('s1', 0.045),
      makeSubagentNoPrice('s2'),
      makeSubagentWithPrice('s3', 0.108),
    ];
    const result = computeSubagentRollup(items);
    expect(result.count).toBe(3);
    expect(result.cost).toBeCloseTo(0.045 + 0.108, 9);
  });

  it('returns cost undefined when ALL subagents have no price data', () => {
    const items: PreparedMessage[] = [
      makeSubagentNoPrice('s1'),
      makeSubagentNoPrice('s2'),
    ];
    const result = computeSubagentRollup(items);
    expect(result.count).toBe(2);
    expect(result.cost).toBeUndefined();
  });

  it('treats communication-type items as non-subagents (not counted)', () => {
    const items: PreparedMessage[] = [
      makeCommunication('comm1'),
      makeCommunication('comm2'),
    ];
    const result = computeSubagentRollup(items);
    expect(result.count).toBe(0);
    expect(result.cost).toBeUndefined();
  });
});

// ─── computeSubagentRollup — matrix transitions ───────────────────────────────

describe('computeSubagentRollup — matrix transitions', () => {
  /**
   * Matrix row: "Running→done transition with fresh REST fetch"
   *
   * Simulates calling the pure helper twice for the same logical subagent —
   * first while it is still running (no price yet), then after the REST fetch
   * returns the completed statistics. Asserts no shared state between the two
   * calls (the helper is stateless).
   */
  it('running → done transition: cost transitions from undefined to final price', () => {
    // First call: subagent has no statistics yet (running, no price)
    const runningItems: PreparedMessage[] = [makeSubagentNoPrice('s1')];
    const runningResult = computeSubagentRollup(runningItems);
    expect(runningResult.count).toBe(1);
    expect(runningResult.cost).toBeUndefined();

    // Second call: same subagent identity, now with completed statistics
    const doneItems: PreparedMessage[] = [
      makeSubagentWithPrice('s1', 0.08),
    ];
    const doneResult = computeSubagentRollup(doneItems);
    expect(doneResult.count).toBe(1);
    expect(doneResult.cost).toBeCloseTo(0.08, 9);

    // Assert no shared state: running result is unchanged after the done call
    expect(runningResult.cost).toBeUndefined();
    expect(runningResult.count).toBe(1);
  });

  /**
   * Matrix row: "Thread-switch during running state"
   *
   * Demonstrates that the helper does not memoize across distinct child arrays.
   * Call 1 comes from thread A (one running subagent, no price).
   * Call 2 comes from thread B (two completed subagents, both priced).
   * Each call must return values that are entirely independent of the other.
   */
  it('thread-switch during running state: results are independent across distinct child arrays', () => {
    // Thread A: one running subagent with no price data
    const threadAItems: PreparedMessage[] = [makeSubagentNoPrice('a1')];
    const threadAResult = computeSubagentRollup(threadAItems);
    expect(threadAResult.count).toBe(1);
    expect(threadAResult.cost).toBeUndefined();

    // Thread B: two completed subagents, both fully priced
    const threadBItems: PreparedMessage[] = [
      makeSubagentWithPrice('b1', 0.05),
      makeSubagentWithPrice('b2', 0.10),
    ];
    const threadBResult = computeSubagentRollup(threadBItems);
    expect(threadBResult.count).toBe(2);
    expect(threadBResult.cost).toBeCloseTo(0.15, 9);

    // Assert that thread A result was not polluted by thread B call
    expect(threadAResult.count).toBe(1);
    expect(threadAResult.cost).toBeUndefined();

    // Assert that thread B result was not polluted by thread A state
    expect(threadBResult.count).toBe(2);
    expect(threadBResult.cost).toBeCloseTo(0.15, 9);
  });
});
