import { createZodDto } from 'nestjs-zod';
import { z } from 'zod';

export const SuggestAgentInstructionsSchema = z.object({
  userRequest: z
    .string()
    .min(1)
    .describe('User request describing how to adjust agent instructions'),
  threadId: z
    .string()
    .optional()
    .describe(
      'Optional thread id to continue a previous suggestion conversation',
    ),
});

export const SuggestAgentInstructionsResponseSchema = z.object({
  instructions: z
    .string()
    .describe('Updated agent instructions generated by the LLM'),
  threadId: z.string().describe('Thread id used for this suggestion session'),
});

export class SuggestAgentInstructionsDto extends createZodDto(
  SuggestAgentInstructionsSchema,
) {}

export class SuggestAgentInstructionsResponseDto extends createZodDto(
  SuggestAgentInstructionsResponseSchema,
) {}

export type SuggestAgentInstructionsRequest = z.infer<
  typeof SuggestAgentInstructionsSchema
>;
export type SuggestAgentInstructionsResponse = z.infer<
  typeof SuggestAgentInstructionsResponseSchema
>;
