import { createZodDto } from 'nestjs-zod';
import { z } from 'zod';

export const SuggestAgentInstructionsSchema = z.object({
  userRequest: z
    .string()
    .min(1)
    .describe('User request describing how to adjust agent instructions'),
  threadId: z
    .string()
    .optional()
    .describe(
      'Optional thread id to continue a previous suggestion conversation',
    ),
  model: z
    .string()
    .trim()
    .min(1)
    .optional()
    .describe('Optional LLM model to use for this suggestion'),
});

export const SuggestAgentInstructionsResponseSchema = z.object({
  instructions: z
    .string()
    .describe('Updated agent instructions generated by the LLM'),
  threadId: z.string().describe('Thread id used for this suggestion session'),
});

export const SuggestGraphInstructionsSchema = z.object({
  userRequest: z
    .string()
    .min(1)
    .describe('User request describing how to adjust agent instructions'),
  model: z
    .string()
    .trim()
    .min(1)
    .optional()
    .describe('Optional LLM model to use for this suggestion'),
});

export const SuggestGraphInstructionsResponseSchema = z.object({
  updates: z
    .array(
      z.object({
        nodeId: z.string().min(1).describe('Agent node id'),
        name: z.string().min(1).optional().describe('Agent display name'),
        instructions: z
          .string()
          .min(1)
          .describe('Updated agent instructions generated by the LLM'),
      }),
    )
    .describe('Only agents with changed instructions are returned'),
});

export const ThreadAnalysisResponseSchema = z.object({
  analysis: z
    .string()
    .describe('LLM-generated analysis and improvement suggestions'),
  conversationId: z
    .string()
    .describe('Identifier of the LLM conversation used for the analysis'),
});

export const ThreadAnalysisRequestSchema = z.object({
  userInput: z
    .string()
    .min(1)
    .max(5000)
    .optional()
    .describe('Optional user-provided input to guide the analysis'),
  threadId: z
    .string()
    .optional()
    .describe(
      'Optional LLM conversation id to continue the existing suggestion thread',
    ),
  model: z
    .string()
    .trim()
    .min(1)
    .optional()
    .describe('Optional LLM model to use for this analysis'),
});

export const KnowledgeContentSuggestionRequestSchema = z.object({
  userRequest: z
    .string()
    .min(1)
    .describe('User request describing knowledge content to create or improve'),
  currentTitle: z
    .string()
    .optional()
    .describe('Optional existing knowledge document title'),
  currentContent: z
    .string()
    .optional()
    .describe('Optional existing knowledge document content'),
  currentTags: z
    .array(z.string().min(1))
    .optional()
    .describe('Optional existing tags for the knowledge document'),
  threadId: z
    .string()
    .optional()
    .describe(
      'Optional thread id to continue a previous suggestion conversation',
    ),
  model: z
    .string()
    .trim()
    .min(1)
    .optional()
    .describe('Optional LLM model to use for this suggestion'),
});

export const KnowledgeContentSuggestionResponseSchema = z.object({
  title: z.string().min(1).describe('Suggested knowledge document title'),
  content: z.string().min(1).describe('Suggested knowledge document content'),
  tags: z
    .array(z.string().min(1))
    .optional()
    .describe('Suggested tags for the knowledge document'),
  threadId: z.string().describe('Thread id used for this suggestion session'),
});

export class SuggestAgentInstructionsDto extends createZodDto(
  SuggestAgentInstructionsSchema,
) {}

export class SuggestAgentInstructionsResponseDto extends createZodDto(
  SuggestAgentInstructionsResponseSchema,
) {}

export class SuggestGraphInstructionsDto extends createZodDto(
  SuggestGraphInstructionsSchema,
) {}

export class SuggestGraphInstructionsResponseDto extends createZodDto(
  SuggestGraphInstructionsResponseSchema,
) {}

export class ThreadAnalysisResponseDto extends createZodDto(
  ThreadAnalysisResponseSchema,
) {}

export class ThreadAnalysisRequestDto extends createZodDto(
  ThreadAnalysisRequestSchema,
) {}

export class KnowledgeContentSuggestionRequestDto extends createZodDto(
  KnowledgeContentSuggestionRequestSchema,
) {}

export class KnowledgeContentSuggestionResponseDto extends createZodDto(
  KnowledgeContentSuggestionResponseSchema,
) {}

export type SuggestAgentInstructionsRequest = z.infer<
  typeof SuggestAgentInstructionsSchema
>;
export type SuggestAgentInstructionsResponse = z.infer<
  typeof SuggestAgentInstructionsResponseSchema
>;
export type SuggestGraphInstructionsRequest = z.infer<
  typeof SuggestGraphInstructionsSchema
>;
export type SuggestGraphInstructionsResponse = z.infer<
  typeof SuggestGraphInstructionsResponseSchema
>;
export type ThreadAnalysisResponse = z.infer<
  typeof ThreadAnalysisResponseSchema
>;
export type ThreadAnalysisRequest = z.infer<typeof ThreadAnalysisRequestSchema>;
export type KnowledgeContentSuggestionRequest = z.infer<
  typeof KnowledgeContentSuggestionRequestSchema
>;
export type KnowledgeContentSuggestionResponse = z.infer<
  typeof KnowledgeContentSuggestionResponseSchema
>;
