/**
 * Thin hand-written client for the thread-store REST endpoints.
 *
 * When `pnpm --filter @geniro/web generate:api` is next run, the autogenerated
 * client will include a typed `ThreadStoreApi`. This wrapper can then be
 * replaced with the generated one.
 */
import axios from 'axios';

import { API_URL } from '../config';

type ThreadStoreEntryMode = 'kv' | 'append';

export interface ThreadStoreEntry {
  id: string;
  threadId: string;
  namespace: string;
  key: string;
  value: unknown;
  mode: ThreadStoreEntryMode;
  authorAgentId: string | null;
  tags: string[] | null;
  createdAt: string;
  updatedAt: string;
}

export interface ThreadStoreNamespaceSummary {
  namespace: string;
  entryCount: number;
  lastUpdatedAt: string;
}

const base = (threadId: string) =>
  `${API_URL}/api/v1/threads/${encodeURIComponent(threadId)}/store`;

export const threadStoreApi = {
  async listNamespaces(
    threadId: string,
  ): Promise<ThreadStoreNamespaceSummary[]> {
    const { data } = await axios.get<ThreadStoreNamespaceSummary[]>(
      base(threadId),
    );
    return data;
  },
  async listEntries(
    threadId: string,
    namespace: string,
    options?: { limit?: number; offset?: number },
  ): Promise<ThreadStoreEntry[]> {
    const { data } = await axios.get<ThreadStoreEntry[]>(
      `${base(threadId)}/${encodeURIComponent(namespace)}`,
      { params: options },
    );
    return data;
  },
};
