import { describe, expect, it } from 'vitest';

import type { ThreadMessageDto } from '../../../../autogenerated';
import { STREAMING_REASONING_FLAG } from '../../../../utils/threadMessages';
import { prepareReadyMessages } from './prepareMessages';
import type { PreparedMessage } from './threadMessagesTypes';

// ── Factory helpers ───────────────────────────────────────────────────────────

/**
 * Minimal valid `ThreadMessageDto`.  Only the fields required by the
 * prepareReadyMessages processing paths are populated; everything else uses
 * safe default values.
 */
const makeMsg = (
  id: string,
  role: string,
  content: string,
  additionalKwargs: Record<string, unknown> = {},
  extra: Partial<
    Pick<
      ThreadMessageDto,
      'createdAt' | 'updatedAt' | 'nodeId' | 'externalThreadId'
    >
  > = {},
): ThreadMessageDto => ({
  id,
  threadId: 'thread-1',
  nodeId: 'node-1',
  externalThreadId: '',
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  ...extra,
  message: {
    id,
    role: role as string,
    content,
    additionalKwargs,
  } as ThreadMessageDto['message'],
});

/** AI message that owns a subagents_run_task tool call. */
const makeSubagentCallMsg = (
  id: string,
  toolCallId: string,
): ThreadMessageDto => ({
  id,
  threadId: 'thread-1',
  nodeId: 'node-1',
  externalThreadId: '',
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  message: {
    id,
    role: 'ai' as string,
    content: '',
    toolCalls: [{ id: toolCallId, name: 'subagents_run_task' }],
  } as ThreadMessageDto['message'],
});

/** Tool message that is the result of a subagents_run_task call. */
const makeSubagentResultMsg = (
  id: string,
  toolCallId: string,
): ThreadMessageDto => ({
  id,
  threadId: 'thread-1',
  nodeId: 'node-1',
  externalThreadId: '',
  createdAt: '2024-01-01T00:01:00.000Z',
  updatedAt: '2024-01-01T00:01:00.000Z',
  message: {
    id,
    role: 'tool' as string,
    content: '',
    name: 'subagents_run_task',
    toolCallId,
  } as ThreadMessageDto['message'],
});

/** Streaming reasoning message carrying the `__streamingReasoning` flag. */
const makeStreamingReasoning = (
  id: string,
  overrides: {
    toolCallId?: string;
    subagentCommunication?: boolean;
    interAgentCommunication?: boolean;
  } = {},
): ThreadMessageDto => {
  const kwargs: Record<string, unknown> = {
    __reasoningId: id,
    [STREAMING_REASONING_FLAG]: true,
  };
  if (overrides.toolCallId) {
    kwargs.__toolCallId = overrides.toolCallId;
  }
  if (overrides.subagentCommunication) {
    kwargs.__subagentCommunication = true;
  }
  if (overrides.interAgentCommunication) {
    kwargs.__interAgentCommunication = true;
  }
  return makeMsg(id, 'reasoning', 'streaming...', kwargs);
};

/** Chat message from inside a subagent run (carries __subagentCommunication). */
const makeSubagentInnerChat = (
  id: string,
  toolCallId: string,
): ThreadMessageDto =>
  makeMsg(id, 'ai', `inner content ${id}`, {
    __toolCallId: toolCallId,
    __subagentCommunication: true,
  });

/** Default minimal options for prepareReadyMessages. */
const defaultOptions = {
  isNodeRunning: false,
  isThreadStopped: false,
};

/** Walk a PreparedMessage tree and collect all items matching a predicate. */
const collectItems = (
  items: PreparedMessage[],
  predicate: (item: PreparedMessage) => boolean,
): PreparedMessage[] => {
  const result: PreparedMessage[] = [];
  const walk = (list: PreparedMessage[]): void => {
    for (const item of list) {
      if (predicate(item)) {
        result.push(item);
      }
      if (
        (item.type === 'subagent' || item.type === 'communication') &&
        item.innerMessages.length > 0
      ) {
        walk(item.innerMessages);
      }
    }
  };
  walk(items);
  return result;
};

/** Convenience: return the first subagent block in the tree. */
const findSubagentBlock = (
  items: PreparedMessage[],
  toolCallId: string,
): (PreparedMessage & { type: 'subagent' }) | undefined => {
  const matches = collectItems(
    items,
    (item) =>
      item.type === 'subagent' &&
      'toolCallId' in item &&
      item.toolCallId === toolCallId,
  );
  return matches[0] as (PreparedMessage & { type: 'subagent' }) | undefined;
};

/** Return all streaming reasoning items found anywhere in the tree. */
const findStreamingReasoning = (
  items: PreparedMessage[],
  reasoningId: string,
): PreparedMessage[] =>
  collectItems(
    items,
    (item) =>
      item.type === 'reasoning' &&
      'message' in item &&
      item.id === `reasoning-${reasoningId}`,
  );

// ── Scenario (a): orphan with __toolCallId routes into executed block ─────────

describe('adoptOrphanStreamingReasoning — keyed by __toolCallId', () => {
  it('(a) streaming reasoning with __toolCallId routes into the matching subagent block when its status is executed', () => {
    // Subagent inner messages arrive WITHOUT the parent AI message (AI message
    // absent — e.g. pagination).  prepareReadyMessages creates a synthetic
    // subagent block (status: 'executed') from the orphaned inner messages.
    // The streaming reasoning carries the same toolCallId but no __subagentCommunication
    // flag, so it is NOT consumed as inner.  adoptOrphanStreamingReasoning must
    // route it into the synthetic block via findBlockByToolCallId, which accepts
    // any status (fixing "reasoning disappears after block completes").
    const msgs: ThreadMessageDto[] = [
      // Orphan inner chat — parent AI msg for 'tc-exec' is absent
      makeSubagentInnerChat('inner-chat-1', 'tc-exec'),
      // Streaming reasoning carrying the same toolCallId but no comm flags
      makeStreamingReasoning('reasoning:r1', { toolCallId: 'tc-exec' }),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    // The synthetic subagent block must exist.
    const block = findSubagentBlock(prepared, 'tc-exec');
    expect(block).toBeDefined();
    expect(block!.status).toBe('executed');

    // The streaming reasoning must be INSIDE the block, not at the root.
    const rootReasoning = prepared.filter(
      (item) =>
        item.type === 'reasoning' && item.id === 'reasoning-reasoning:r1',
    );
    expect(rootReasoning).toHaveLength(0);

    const innerReasoning = block!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);
  });

  it('(b) two concurrent subagent blocks each receive only their own streaming reasoning', () => {
    const msgs: ThreadMessageDto[] = [
      // Orphan inner messages for subagent A and B (no parent AI msg for either)
      makeSubagentInnerChat('inner-a', 'tc-A'),
      makeSubagentInnerChat('inner-b', 'tc-B'),
      // Streaming reasoning for A — must end up only inside block A
      makeStreamingReasoning('reasoning:a', { toolCallId: 'tc-A' }),
      // Streaming reasoning for B — must end up only inside block B
      makeStreamingReasoning('reasoning:b', { toolCallId: 'tc-B' }),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    const blockA = findSubagentBlock(prepared, 'tc-A');
    const blockB = findSubagentBlock(prepared, 'tc-B');

    expect(blockA).toBeDefined();
    expect(blockB).toBeDefined();

    // Block A gets reasoning:a, not reasoning:b
    const reasoningInA = blockA!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(reasoningInA).toHaveLength(1);
    expect(reasoningInA[0].id).toBe('reasoning-reasoning:a');

    // Block B gets reasoning:b, not reasoning:a
    const reasoningInB = blockB!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(reasoningInB).toHaveLength(1);
    expect(reasoningInB[0].id).toBe('reasoning-reasoning:b');

    // Neither reasoning appears at the root level
    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(0);
  });
});

// ── Scenario (c): orphan without __toolCallId falls back to deepest active ────

describe('adoptOrphanStreamingReasoning — unkeyed falls back to findDeepestActiveBlock', () => {
  it('(c) orphan without __toolCallId is adopted by the deepest active (calling) block', () => {
    // A subagents_run_task call is in progress (no result yet, isNodeRunning=true).
    // The streaming reasoning has no __toolCallId — it should be routed via the
    // existing findDeepestActiveBlock heuristic (existing behavior preserved).
    const msgs: ThreadMessageDto[] = [
      makeSubagentCallMsg('ai-calling', 'tc-calling'),
      // No tool result → block status = 'calling'
      // Streaming reasoning with no toolCallId
      makeStreamingReasoning('reasoning:unkeyed'),
    ];

    const prepared = prepareReadyMessages(msgs, {
      ...defaultOptions,
      isNodeRunning: true,
    });

    const block = findSubagentBlock(prepared, 'tc-calling');
    expect(block).toBeDefined();
    expect(block!.status).toBe('calling');

    // Reasoning must be inside the calling block, not at the root.
    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(0);

    const innerReasoning = block!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);
  });
});

// ── Scenario (d): top-level reasoning with no active block stays at root ──────

describe('adoptOrphanStreamingReasoning — no block present (G5)', () => {
  it('(d) streaming reasoning with no matching block stays at the root level', () => {
    // When there are no subagent/communication blocks in the prepared list,
    // a streaming reasoning orphan must remain at the root.  This preserves
    // the top-level reasoning use case (G5: ordinary agent reasoning is visible).
    const msgs: ThreadMessageDto[] = [
      // Just a streaming reasoning — no blocks at all
      makeStreamingReasoning('reasoning:toplevel'),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(1);
    expect(rootReasoning[0].id).toBe('reasoning-reasoning:toplevel');
  });

  it('(d) streaming reasoning with a non-matching __toolCallId stays at root when no block matches', () => {
    // When __toolCallId is set but no block in the prepared list has that
    // toolCallId, the orphan falls back to findDeepestActiveBlock.  With no
    // active blocks, it remains at root.
    const msgs: ThreadMessageDto[] = [
      makeStreamingReasoning('reasoning:nomatch', {
        toolCallId: 'tc-nonexistent',
      }),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(1);
  });
});

// ── Scenario: persisted vs streaming subagent-inner reasoning (pre-scan wins) ──

describe('subagent-inner reasoning pre-scan grouping', () => {
  it('routes persisted subagent reasoning (no streaming flag) into the SubagentBlock via pre-scan', () => {
    // Persisted reasoning after reload: carries __toolCallId + __subagentCommunication,
    // but NOT STREAMING_REASONING_FLAG.  The pre-scan at prepareMessages.ts:391-428
    // groups it into subagentInnerByToolCallId so it renders inside the SubagentBlock
    // rather than leaking to the parent timeline.
    const msgs: ThreadMessageDto[] = [
      makeSubagentCallMsg('ai-call-1', 'tc1'),
      makeMsg('reasoning-1', 'reasoning', 'thinking...', {
        __toolCallId: 'tc1',
        __subagentCommunication: true,
        __reasoningId: 'reasoning:chunk-a',
      }),
      makeSubagentResultMsg('tool-result-1', 'tc1'),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    // Exactly one top-level item, of type 'subagent'.
    expect(prepared).toHaveLength(1);
    expect(prepared[0].type).toBe('subagent');

    // Reasoning is inside the subagent block.
    const block = findSubagentBlock(prepared, 'tc1');
    expect(block).toBeDefined();
    const innerReasoning = block!.innerMessages.filter(
      (m) => m.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);

    // And NOT at the top level.
    const rootReasoning = prepared.filter((m) => m.type === 'reasoning');
    expect(rootReasoning).toHaveLength(0);
  });

  it('subagent-tagged streaming reasoning with matching __toolCallId is routed by pre-scan (not orphan adoption)', () => {
    // Mid-run streaming: no tool result yet, reasoning carries both STREAMING_REASONING_FLAG
    // (from makeStreamingReasoning) AND __toolCallId matching a loaded subagents_run_task
    // call.  Because the pre-scan runs BEFORE adoptOrphanStreamingReasoning, the
    // reasoning ends up inside the 'calling' subagent block via pre-scan — not via
    // orphan adoption.  The end result looks the same, but this test locks in
    // the execution order so future refactors don't silently route through orphan
    // adoption.
    const msgs: ThreadMessageDto[] = [
      makeSubagentCallMsg('ai-call-1', 'tc1'),
      makeStreamingReasoning('reasoning:chunk-a', {
        toolCallId: 'tc1',
        subagentCommunication: true,
      }),
    ];

    const prepared = prepareReadyMessages(msgs, {
      ...defaultOptions,
      isNodeRunning: true,
    });

    // The subagent block ('calling' status — no tool result yet) contains the reasoning.
    const block = findSubagentBlock(prepared, 'tc1');
    expect(block).toBeDefined();
    const innerReasoning = block!.innerMessages.filter(
      (m) => m.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);

    // No top-level reasoning — neither pre-scan nor orphan adoption must duplicate.
    expect(prepared.filter((m) => m.type === 'reasoning')).toHaveLength(0);
  });
});
