import { describe, expect, it } from 'vitest';

import type { ThreadMessageDto } from '../../../../autogenerated';
import { STREAMING_REASONING_FLAG } from '../../../../utils/threadMessages';
import {
  _accumulatePreparedStatistics,
  prepareReadyMessages,
} from './prepareMessages';
import type { PreparedMessage } from './threadMessagesTypes';

// ── Factory helpers ───────────────────────────────────────────────────────────

/**
 * Minimal valid `ThreadMessageDto`.  Only the fields required by the
 * prepareReadyMessages processing paths are populated; everything else uses
 * safe default values.
 */
const makeMsg = (
  id: string,
  role: string,
  content: string,
  additionalKwargs: Record<string, unknown> = {},
  extra: Partial<
    Pick<
      ThreadMessageDto,
      'createdAt' | 'updatedAt' | 'nodeId' | 'externalThreadId'
    >
  > = {},
): ThreadMessageDto => ({
  id,
  threadId: 'thread-1',
  nodeId: 'node-1',
  externalThreadId: '',
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  ...extra,
  message: {
    id,
    role: role as string,
    content,
    additionalKwargs,
  } as ThreadMessageDto['message'],
});

/** AI message that owns a subagents_run_task tool call. */
const makeSubagentCallMsg = (
  id: string,
  toolCallId: string,
): ThreadMessageDto => ({
  id,
  threadId: 'thread-1',
  nodeId: 'node-1',
  externalThreadId: '',
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  message: {
    id,
    role: 'ai' as string,
    content: '',
    toolCalls: [{ id: toolCallId, name: 'subagents_run_task' }],
  } as ThreadMessageDto['message'],
});

/** Tool message that is the result of a subagents_run_task call. */
const makeSubagentResultMsg = (
  id: string,
  toolCallId: string,
): ThreadMessageDto => ({
  id,
  threadId: 'thread-1',
  nodeId: 'node-1',
  externalThreadId: '',
  createdAt: '2024-01-01T00:01:00.000Z',
  updatedAt: '2024-01-01T00:01:00.000Z',
  message: {
    id,
    role: 'tool' as string,
    content: '',
    name: 'subagents_run_task',
    toolCallId,
  } as ThreadMessageDto['message'],
});

/** Streaming reasoning message carrying the `__streamingReasoning` flag. */
const makeStreamingReasoning = (
  id: string,
  overrides: {
    toolCallId?: string;
    subagentCommunication?: boolean;
    interAgentCommunication?: boolean;
  } = {},
): ThreadMessageDto => {
  const kwargs: Record<string, unknown> = {
    __reasoningId: id,
    [STREAMING_REASONING_FLAG]: true,
  };
  if (overrides.toolCallId) {
    kwargs.__toolCallId = overrides.toolCallId;
  }
  if (overrides.subagentCommunication) {
    kwargs.__subagentCommunication = true;
  }
  if (overrides.interAgentCommunication) {
    kwargs.__interAgentCommunication = true;
  }
  return makeMsg(id, 'reasoning', 'streaming...', kwargs);
};

/** Chat message from inside a subagent run (carries __subagentCommunication). */
const makeSubagentInnerChat = (
  id: string,
  toolCallId: string,
): ThreadMessageDto =>
  makeMsg(id, 'ai', `inner content ${id}`, {
    __toolCallId: toolCallId,
    __subagentCommunication: true,
  });

/** Default minimal options for prepareReadyMessages. */
const defaultOptions = {
  isNodeRunning: false,
  isThreadStopped: false,
};

/** Walk a PreparedMessage tree and collect all items matching a predicate. */
const collectItems = (
  items: PreparedMessage[],
  predicate: (item: PreparedMessage) => boolean,
): PreparedMessage[] => {
  const result: PreparedMessage[] = [];
  const walk = (list: PreparedMessage[]): void => {
    for (const item of list) {
      if (predicate(item)) {
        result.push(item);
      }
      if (
        (item.type === 'subagent' || item.type === 'communication') &&
        item.innerMessages.length > 0
      ) {
        walk(item.innerMessages);
      }
    }
  };
  walk(items);
  return result;
};

/** Convenience: return the first subagent block in the tree. */
const findSubagentBlock = (
  items: PreparedMessage[],
  toolCallId: string,
): (PreparedMessage & { type: 'subagent' }) | undefined => {
  const matches = collectItems(
    items,
    (item) =>
      item.type === 'subagent' &&
      'toolCallId' in item &&
      item.toolCallId === toolCallId,
  );
  return matches[0] as (PreparedMessage & { type: 'subagent' }) | undefined;
};

/** Return all streaming reasoning items found anywhere in the tree. */
const findStreamingReasoning = (
  items: PreparedMessage[],
  reasoningId: string,
): PreparedMessage[] =>
  collectItems(
    items,
    (item) =>
      item.type === 'reasoning' &&
      'message' in item &&
      item.id === `reasoning-${reasoningId}`,
  );

// ── Scenario (a): orphan with __toolCallId routes into executed block ─────────

describe('adoptOrphanStreamingReasoning — keyed by __toolCallId', () => {
  it('(a) streaming reasoning with __toolCallId routes into the matching subagent block when its status is executed', () => {
    // Subagent inner messages arrive WITHOUT the parent AI message (AI message
    // absent — e.g. pagination).  prepareReadyMessages creates a synthetic
    // subagent block (status: 'executed') from the orphaned inner messages.
    // The streaming reasoning carries the same toolCallId but no __subagentCommunication
    // flag, so it is NOT consumed as inner.  adoptOrphanStreamingReasoning must
    // route it into the synthetic block via findBlockByToolCallId, which accepts
    // any status (fixing "reasoning disappears after block completes").
    const msgs: ThreadMessageDto[] = [
      // Orphan inner chat — parent AI msg for 'tc-exec' is absent
      makeSubagentInnerChat('inner-chat-1', 'tc-exec'),
      // Streaming reasoning carrying the same toolCallId but no comm flags
      makeStreamingReasoning('reasoning:r1', { toolCallId: 'tc-exec' }),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    // The synthetic subagent block must exist.
    const block = findSubagentBlock(prepared, 'tc-exec');
    expect(block).toBeDefined();
    expect(block!.status).toBe('executed');

    // The streaming reasoning must be INSIDE the block, not at the root.
    const rootReasoning = prepared.filter(
      (item) =>
        item.type === 'reasoning' && item.id === 'reasoning-reasoning:r1',
    );
    expect(rootReasoning).toHaveLength(0);

    const innerReasoning = block!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);
  });

  it('(b) two concurrent subagent blocks each receive only their own streaming reasoning', () => {
    const msgs: ThreadMessageDto[] = [
      // Orphan inner messages for subagent A and B (no parent AI msg for either)
      makeSubagentInnerChat('inner-a', 'tc-A'),
      makeSubagentInnerChat('inner-b', 'tc-B'),
      // Streaming reasoning for A — must end up only inside block A
      makeStreamingReasoning('reasoning:a', { toolCallId: 'tc-A' }),
      // Streaming reasoning for B — must end up only inside block B
      makeStreamingReasoning('reasoning:b', { toolCallId: 'tc-B' }),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    const blockA = findSubagentBlock(prepared, 'tc-A');
    const blockB = findSubagentBlock(prepared, 'tc-B');

    expect(blockA).toBeDefined();
    expect(blockB).toBeDefined();

    // Block A gets reasoning:a, not reasoning:b
    const reasoningInA = blockA!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(reasoningInA).toHaveLength(1);
    expect(reasoningInA[0].id).toBe('reasoning-reasoning:a');

    // Block B gets reasoning:b, not reasoning:a
    const reasoningInB = blockB!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(reasoningInB).toHaveLength(1);
    expect(reasoningInB[0].id).toBe('reasoning-reasoning:b');

    // Neither reasoning appears at the root level
    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(0);
  });
});

// ── Scenario (c): orphan without __toolCallId falls back to deepest active ────

describe('adoptOrphanStreamingReasoning — unkeyed falls back to findDeepestActiveBlock', () => {
  it('(c) orphan without __toolCallId is adopted by the deepest active (calling) block', () => {
    // A subagents_run_task call is in progress (no result yet, isNodeRunning=true).
    // The streaming reasoning has no __toolCallId — it should be routed via the
    // existing findDeepestActiveBlock heuristic (existing behavior preserved).
    const msgs: ThreadMessageDto[] = [
      makeSubagentCallMsg('ai-calling', 'tc-calling'),
      // No tool result → block status = 'calling'
      // Streaming reasoning with no toolCallId
      makeStreamingReasoning('reasoning:unkeyed'),
    ];

    const prepared = prepareReadyMessages(msgs, {
      ...defaultOptions,
      isNodeRunning: true,
    });

    const block = findSubagentBlock(prepared, 'tc-calling');
    expect(block).toBeDefined();
    expect(block!.status).toBe('calling');

    // Reasoning must be inside the calling block, not at the root.
    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(0);

    const innerReasoning = block!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);
  });
});

// ── Scenario (d): top-level reasoning with no active block stays at root ──────

describe('adoptOrphanStreamingReasoning — no block present (G5)', () => {
  it('(d) streaming reasoning with no matching block stays at the root level', () => {
    // When there are no subagent/communication blocks in the prepared list,
    // a streaming reasoning orphan must remain at the root.  This preserves
    // the top-level reasoning use case (G5: ordinary agent reasoning is visible).
    const msgs: ThreadMessageDto[] = [
      // Just a streaming reasoning — no blocks at all
      makeStreamingReasoning('reasoning:toplevel'),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(1);
    expect(rootReasoning[0].id).toBe('reasoning-reasoning:toplevel');
  });

  it('(d) streaming reasoning with a non-matching __toolCallId stays at root when no block matches', () => {
    // When __toolCallId is set but no block in the prepared list has that
    // toolCallId, the orphan falls back to findDeepestActiveBlock.  With no
    // active blocks, it remains at root.
    const msgs: ThreadMessageDto[] = [
      makeStreamingReasoning('reasoning:nomatch', {
        toolCallId: 'tc-nonexistent',
      }),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(1);
  });
});

// ── Scenario: persisted vs streaming subagent-inner reasoning (pre-scan wins) ──

describe('subagent-inner reasoning pre-scan grouping', () => {
  it('routes persisted subagent reasoning (no streaming flag) into the SubagentBlock via pre-scan', () => {
    // Persisted reasoning after reload: carries __toolCallId + __subagentCommunication,
    // but NOT STREAMING_REASONING_FLAG.  The pre-scan at prepareMessages.ts:391-428
    // groups it into subagentInnerByToolCallId so it renders inside the SubagentBlock
    // rather than leaking to the parent timeline.
    const msgs: ThreadMessageDto[] = [
      makeSubagentCallMsg('ai-call-1', 'tc1'),
      makeMsg('reasoning-1', 'reasoning', 'thinking...', {
        __toolCallId: 'tc1',
        __subagentCommunication: true,
        __reasoningId: 'reasoning:chunk-a',
      }),
      makeSubagentResultMsg('tool-result-1', 'tc1'),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    // Exactly one top-level item, of type 'subagent'.
    expect(prepared).toHaveLength(1);
    expect(prepared[0].type).toBe('subagent');

    // Reasoning is inside the subagent block.
    const block = findSubagentBlock(prepared, 'tc1');
    expect(block).toBeDefined();
    const innerReasoning = block!.innerMessages.filter(
      (m) => m.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);

    // And NOT at the top level.
    const rootReasoning = prepared.filter((m) => m.type === 'reasoning');
    expect(rootReasoning).toHaveLength(0);
  });

  it('subagent-tagged streaming reasoning with matching __toolCallId is routed by pre-scan (not orphan adoption)', () => {
    // Mid-run streaming: no tool result yet, reasoning carries both STREAMING_REASONING_FLAG
    // (from makeStreamingReasoning) AND __toolCallId matching a loaded subagents_run_task
    // call.  Because the pre-scan runs BEFORE adoptOrphanStreamingReasoning, the
    // reasoning ends up inside the 'calling' subagent block via pre-scan — not via
    // orphan adoption.  The end result looks the same, but this test locks in
    // the execution order so future refactors don't silently route through orphan
    // adoption.
    const msgs: ThreadMessageDto[] = [
      makeSubagentCallMsg('ai-call-1', 'tc1'),
      makeStreamingReasoning('reasoning:chunk-a', {
        toolCallId: 'tc1',
        subagentCommunication: true,
      }),
    ];

    const prepared = prepareReadyMessages(msgs, {
      ...defaultOptions,
      isNodeRunning: true,
    });

    // The subagent block ('calling' status — no tool result yet) contains the reasoning.
    const block = findSubagentBlock(prepared, 'tc1');
    expect(block).toBeDefined();
    const innerReasoning = block!.innerMessages.filter(
      (m) => m.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);

    // No top-level reasoning — neither pre-scan nor orphan adoption must duplicate.
    expect(prepared.filter((m) => m.type === 'reasoning')).toHaveLength(0);
  });
});

// ── accumulatePreparedStatistics — Change 1 regression guard ─────────────────
//
// These scenarios verify that tool items do NOT double-count price/tokens that
// are already contributed by their sibling chat item (which carries the same
// requestTokenUsage reference from the parent AI message DTO).

describe('accumulatePreparedStatistics', () => {
  // Minimal required fields for a ThreadMessageDto used as a chat item's message.
  const makeMinimalDto = (
    id: string,
    requestTokenUsage?: ThreadMessageDto['requestTokenUsage'],
  ): ThreadMessageDto => ({
    id,
    threadId: 'thread-1',
    nodeId: 'node-1',
    externalThreadId: '',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    requestTokenUsage,
    message: {
      id,
      role: 'ai',
      content: 'hello',
    } as ThreadMessageDto['message'],
  });

  it('1.1 — chat + 2 tool siblings sharing requestTokenUsage: totalPrice and totalTokens counted once', () => {
    // Regression guard for the (N+1)x double-count: a single AI turn produces
    // one chat PreparedMessage and N tool PreparedMessages, all carrying the
    // same requestTokenUsage. Only the chat item must contribute to
    // totalPrice/totalTokens; tool items contribute only durationMs + count.
    const sharedUsage: ThreadMessageDto['requestTokenUsage'] = {
      inputTokens: 600,
      outputTokens: 400,
      totalTokens: 1000,
      totalPrice: 0.05,
    };

    const chatItem: PreparedMessage = {
      type: 'chat',
      id: 'chat-1',
      message: makeMinimalDto('chat-1', sharedUsage),
    };

    const toolItem1: PreparedMessage = {
      type: 'tool',
      id: 'tool-1',
      name: 'search',
      status: 'executed',
      requestTokenUsage: sharedUsage,
    };

    const toolItem2: PreparedMessage = {
      type: 'tool',
      id: 'tool-2',
      name: 'fetch',
      status: 'executed',
      requestTokenUsage: sharedUsage,
    };

    const stats = _accumulatePreparedStatistics([
      chatItem,
      toolItem1,
      toolItem2,
    ]);

    expect(stats).toBeDefined();
    // totalPrice and totalTokens must come from the chat item only — NOT tripled.
    expect(stats!.usage!.totalPrice).toBe(0.05);
    expect(stats!.usage!.totalTokens).toBe(1000);
  });

  it('1.2 — 3 tool items with durationMs and no sibling chat: totalPrice=0, totalTokens=0, durationMs=sum', () => {
    // When tool items have durationMs but no sibling chat, they must not
    // contribute any price or tokens. durationMs is accumulated normally, and
    // count equals the number of tool items (each one is a contributing signal).
    const toolA: PreparedMessage = {
      type: 'tool',
      id: 'tool-a',
      name: 'shell',
      status: 'executed',
      durationMs: 100,
    };

    const toolB: PreparedMessage = {
      type: 'tool',
      id: 'tool-b',
      name: 'shell',
      status: 'executed',
      durationMs: 200,
    };

    const toolC: PreparedMessage = {
      type: 'tool',
      id: 'tool-c',
      name: 'shell',
      status: 'executed',
      durationMs: 300,
    };

    const stats = _accumulatePreparedStatistics([toolA, toolB, toolC]);

    expect(stats).toBeDefined();
    // No chat item → no price or tokens.
    expect(stats!.usage!.totalPrice).toBeUndefined();
    expect(stats!.usage!.totalTokens).toBeUndefined();
    // durationMs is the sum across all three tool items.
    expect(stats!.usage!.durationMs).toBe(600);
    // All three tool items contribute to count (hasDuration=true for each);
    // count is exposed indirectly — a non-undefined return implies count >= 1,
    // and each tool item with durationMs fires count++. We assert the full
    // durationMs sum as the proxy for count===3 (each item contributed once).
  });

  it('1.3 — communication child block + 2 outer chat items: totalPrice accumulates from both sources', () => {
    // A communication/subagent block contributes its pre-computed statistics as
    // a single item to the parent accumulator; outer chat items contribute their
    // own requestTokenUsage. Together they must sum correctly.
    const chatItem1: PreparedMessage = {
      type: 'chat',
      id: 'outer-chat-1',
      message: makeMinimalDto('outer-chat-1', {
        inputTokens: 100,
        outputTokens: 100,
        totalTokens: 200,
        totalPrice: 0.02,
      }),
    };

    const chatItem2: PreparedMessage = {
      type: 'chat',
      id: 'outer-chat-2',
      message: makeMinimalDto('outer-chat-2', {
        inputTokens: 100,
        outputTokens: 100,
        totalTokens: 200,
        totalPrice: 0.02,
      }),
    };

    const communicationBlock: PreparedMessage = {
      type: 'communication',
      id: 'comm-1',
      toolCallId: 'tc-comm-1',
      innerMessages: [],
      status: 'executed',
      statistics: {
        usage: {
          totalPrice: 0.1,
          totalTokens: 500,
          durationMs: 1000,
        },
      },
    };

    const stats = _accumulatePreparedStatistics([
      chatItem1,
      communicationBlock,
      chatItem2,
    ]);

    expect(stats).toBeDefined();
    // outer chat 1 ($0.02) + communication block ($0.10) + outer chat 2 ($0.02) = $0.14
    expect(stats!.usage!.totalPrice).toBeCloseTo(0.14, 10);
    expect(stats!.usage!.totalTokens).toBe(900); // 200 + 500 + 200
  });
});
