// This file is auto-generated by @hey-api/openapi-ts

export const CreateGraphDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    schema: {
      type: 'object',
      properties: {
        nodes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'string',
              },
              template: {
                type: 'string',
              },
              config: {
                type: 'object',
                propertyNames: {
                  type: 'string',
                },
                additionalProperties: {},
              },
            },
            required: ['id', 'template', 'config'],
          },
        },
        edges: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              from: {
                type: 'string',
              },
              to: {
                type: 'string',
              },
              label: {
                type: 'string',
              },
            },
            required: ['from', 'to'],
          },
        },
      },
      required: ['nodes'],
    },
    metadata: {
      anyOf: [
        {
          type: 'object',
          properties: {
            nodes: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: {
                    type: 'string',
                  },
                  x: {
                    type: 'number',
                  },
                  y: {
                    type: 'number',
                  },
                  name: {
                    type: 'string',
                  },
                },
                required: ['id'],
              },
            },
            zoom: {
              type: 'number',
            },
            x: {
              type: 'number',
            },
            y: {
              type: 'number',
            },
          },
          additionalProperties: {},
        },
        {
          type: 'null',
        },
      ],
    },
    temporary: {
      anyOf: [
        {
          default: false,
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  required: ['name', 'schema'],
} as const;

export const GraphDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
      pattern:
        '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
    },
    name: {
      type: 'string',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    error: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    version: {
      type: 'string',
    },
    targetVersion: {
      type: 'string',
    },
    schema: {
      type: 'object',
      properties: {
        nodes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'string',
              },
              template: {
                type: 'string',
              },
              config: {
                type: 'object',
                propertyNames: {
                  type: 'string',
                },
                additionalProperties: {},
              },
            },
            required: ['id', 'template', 'config'],
          },
        },
        edges: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              from: {
                type: 'string',
              },
              to: {
                type: 'string',
              },
              label: {
                type: 'string',
              },
            },
            required: ['from', 'to'],
          },
        },
      },
      required: ['nodes'],
    },
    status: {
      type: 'string',
      enum: ['created', 'compiling', 'running', 'stopped', 'error'],
    },
    metadata: {
      anyOf: [
        {
          type: 'object',
          properties: {
            nodes: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: {
                    type: 'string',
                  },
                  x: {
                    type: 'number',
                  },
                  y: {
                    type: 'number',
                  },
                  name: {
                    type: 'string',
                  },
                },
                required: ['id'],
              },
            },
            zoom: {
              type: 'number',
            },
            x: {
              type: 'number',
            },
            y: {
              type: 'number',
            },
          },
          additionalProperties: {},
        },
        {
          type: 'null',
        },
      ],
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
      pattern:
        '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
      pattern:
        '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
    },
    temporary: {
      anyOf: [
        {
          default: false,
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  required: [
    'id',
    'name',
    'version',
    'targetVersion',
    'schema',
    'status',
    'createdAt',
    'updatedAt',
  ],
} as const;

export const GraphNodeWithStatusDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
    template: {
      type: 'string',
    },
    type: {
      type: 'string',
      enum: ['runtime', 'tool', 'simpleAgent', 'trigger', 'resource'],
    },
    status: {
      type: 'string',
      enum: ['stopped', 'starting', 'running', 'idle'],
    },
    config: {},
    error: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    metadata: {
      type: 'object',
      properties: {
        threadId: {
          type: 'string',
        },
        runId: {
          type: 'string',
        },
        parentThreadId: {
          type: 'string',
        },
      },
    },
    additionalNodeMetadata: {
      type: 'object',
      propertyNames: {
        type: 'string',
      },
      additionalProperties: {},
    },
  },
  required: ['id', 'name', 'template', 'type', 'status', 'config'],
} as const;

export const UpdateGraphDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    schema: {
      type: 'object',
      properties: {
        nodes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'string',
              },
              template: {
                type: 'string',
              },
              config: {
                type: 'object',
                propertyNames: {
                  type: 'string',
                },
                additionalProperties: {},
              },
            },
            required: ['id', 'template', 'config'],
          },
        },
        edges: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              from: {
                type: 'string',
              },
              to: {
                type: 'string',
              },
              label: {
                type: 'string',
              },
            },
            required: ['from', 'to'],
          },
        },
      },
      required: ['nodes'],
    },
    metadata: {
      anyOf: [
        {
          type: 'object',
          properties: {
            nodes: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: {
                    type: 'string',
                  },
                  x: {
                    type: 'number',
                  },
                  y: {
                    type: 'number',
                  },
                  name: {
                    type: 'string',
                  },
                },
                required: ['id'],
              },
            },
            zoom: {
              type: 'number',
            },
            x: {
              type: 'number',
            },
            y: {
              type: 'number',
            },
          },
          additionalProperties: {},
        },
        {
          type: 'null',
        },
      ],
    },
    temporary: {
      anyOf: [
        {
          default: false,
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
    },
    currentVersion: {
      type: 'string',
    },
  },
  required: ['currentVersion'],
  additionalProperties: false,
} as const;

export const UpdateGraphResponseDtoSchema = {
  type: 'object',
  properties: {
    graph: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          format: 'uuid',
          pattern:
            '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
        },
        name: {
          type: 'string',
        },
        description: {
          anyOf: [
            {
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
        error: {
          anyOf: [
            {
              type: 'string',
            },
            {
              type: 'null',
            },
          ],
        },
        version: {
          type: 'string',
        },
        targetVersion: {
          type: 'string',
        },
        schema: {
          type: 'object',
          properties: {
            nodes: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: {
                    type: 'string',
                  },
                  template: {
                    type: 'string',
                  },
                  config: {
                    type: 'object',
                    propertyNames: {
                      type: 'string',
                    },
                    additionalProperties: {},
                  },
                },
                required: ['id', 'template', 'config'],
              },
            },
            edges: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  from: {
                    type: 'string',
                  },
                  to: {
                    type: 'string',
                  },
                  label: {
                    type: 'string',
                  },
                },
                required: ['from', 'to'],
              },
            },
          },
          required: ['nodes'],
        },
        status: {
          type: 'string',
          enum: ['created', 'compiling', 'running', 'stopped', 'error'],
        },
        metadata: {
          anyOf: [
            {
              type: 'object',
              properties: {
                nodes: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                      },
                      x: {
                        type: 'number',
                      },
                      y: {
                        type: 'number',
                      },
                      name: {
                        type: 'string',
                      },
                    },
                    required: ['id'],
                  },
                },
                zoom: {
                  type: 'number',
                },
                x: {
                  type: 'number',
                },
                y: {
                  type: 'number',
                },
              },
              additionalProperties: {},
            },
            {
              type: 'null',
            },
          ],
        },
        createdAt: {
          type: 'string',
          format: 'date-time',
          pattern:
            '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
        },
        updatedAt: {
          type: 'string',
          format: 'date-time',
          pattern:
            '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
        },
        temporary: {
          anyOf: [
            {
              default: false,
              type: 'boolean',
            },
            {
              type: 'null',
            },
          ],
        },
      },
      required: [
        'id',
        'name',
        'version',
        'targetVersion',
        'schema',
        'status',
        'createdAt',
        'updatedAt',
      ],
    },
    revision: {
      anyOf: [
        {
          type: 'object',
          properties: {
            id: {
              type: 'string',
              format: 'uuid',
              pattern:
                '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
            },
            graphId: {
              type: 'string',
              format: 'uuid',
              pattern:
                '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
            },
            baseVersion: {
              type: 'string',
            },
            toVersion: {
              type: 'string',
            },
            configurationDiff: {
              type: 'array',
              items: {
                anyOf: [
                  {
                    type: 'object',
                    properties: {
                      op: {
                        type: 'string',
                        const: 'add',
                      },
                      path: {
                        type: 'string',
                      },
                      value: {},
                    },
                    required: ['op', 'path', 'value'],
                  },
                  {
                    type: 'object',
                    properties: {
                      op: {
                        type: 'string',
                        const: 'remove',
                      },
                      path: {
                        type: 'string',
                      },
                    },
                    required: ['op', 'path'],
                  },
                  {
                    type: 'object',
                    properties: {
                      op: {
                        type: 'string',
                        const: 'replace',
                      },
                      path: {
                        type: 'string',
                      },
                      value: {},
                    },
                    required: ['op', 'path', 'value'],
                  },
                  {
                    type: 'object',
                    properties: {
                      op: {
                        type: 'string',
                        const: 'move',
                      },
                      from: {
                        type: 'string',
                      },
                      path: {
                        type: 'string',
                      },
                    },
                    required: ['op', 'from', 'path'],
                  },
                  {
                    type: 'object',
                    properties: {
                      op: {
                        type: 'string',
                        const: 'copy',
                      },
                      from: {
                        type: 'string',
                      },
                      path: {
                        type: 'string',
                      },
                    },
                    required: ['op', 'from', 'path'],
                  },
                  {
                    type: 'object',
                    properties: {
                      op: {
                        type: 'string',
                        const: 'test',
                      },
                      path: {
                        type: 'string',
                      },
                      value: {},
                    },
                    required: ['op', 'path', 'value'],
                  },
                ],
              },
            },
            clientSchema: {
              type: 'object',
              properties: {
                nodes: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                      },
                      template: {
                        type: 'string',
                      },
                      config: {
                        type: 'object',
                        propertyNames: {
                          type: 'string',
                        },
                        additionalProperties: {},
                      },
                    },
                    required: ['id', 'template', 'config'],
                  },
                },
                edges: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      from: {
                        type: 'string',
                      },
                      to: {
                        type: 'string',
                      },
                      label: {
                        type: 'string',
                      },
                    },
                    required: ['from', 'to'],
                  },
                },
              },
              required: ['nodes'],
            },
            newSchema: {
              type: 'object',
              properties: {
                nodes: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                      },
                      template: {
                        type: 'string',
                      },
                      config: {
                        type: 'object',
                        propertyNames: {
                          type: 'string',
                        },
                        additionalProperties: {},
                      },
                    },
                    required: ['id', 'template', 'config'],
                  },
                },
                edges: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      from: {
                        type: 'string',
                      },
                      to: {
                        type: 'string',
                      },
                      label: {
                        type: 'string',
                      },
                    },
                    required: ['from', 'to'],
                  },
                },
              },
              required: ['nodes'],
            },
            status: {
              type: 'string',
              enum: ['pending', 'applying', 'applied', 'failed'],
            },
            error: {
              type: 'string',
            },
            createdAt: {
              type: 'string',
              format: 'date-time',
              pattern:
                '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
            },
            updatedAt: {
              type: 'string',
              format: 'date-time',
              pattern:
                '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
            },
          },
          required: [
            'id',
            'graphId',
            'baseVersion',
            'toVersion',
            'configurationDiff',
            'clientSchema',
            'newSchema',
            'status',
            'createdAt',
            'updatedAt',
          ],
        },
        {
          type: 'null',
        },
      ],
    },
  },
  required: ['graph'],
} as const;

export const ExecuteTriggerDtoSchema = {
  type: 'object',
  properties: {
    messages: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'string',
      },
    },
    threadSubId: {
      type: 'string',
    },
    async: {
      type: 'boolean',
    },
  },
  required: ['messages'],
} as const;

export const ExecuteTriggerResponseDtoSchema = {
  type: 'object',
  properties: {
    threadId: {
      type: 'string',
    },
    checkpointNs: {
      type: 'string',
    },
  },
  required: ['threadId'],
} as const;

export const GraphRevisionDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
      pattern:
        '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
    },
    graphId: {
      type: 'string',
      format: 'uuid',
      pattern:
        '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
    },
    baseVersion: {
      type: 'string',
    },
    toVersion: {
      type: 'string',
    },
    configurationDiff: {
      type: 'array',
      items: {
        anyOf: [
          {
            type: 'object',
            properties: {
              op: {
                type: 'string',
                const: 'add',
              },
              path: {
                type: 'string',
              },
              value: {},
            },
            required: ['op', 'path', 'value'],
          },
          {
            type: 'object',
            properties: {
              op: {
                type: 'string',
                const: 'remove',
              },
              path: {
                type: 'string',
              },
            },
            required: ['op', 'path'],
          },
          {
            type: 'object',
            properties: {
              op: {
                type: 'string',
                const: 'replace',
              },
              path: {
                type: 'string',
              },
              value: {},
            },
            required: ['op', 'path', 'value'],
          },
          {
            type: 'object',
            properties: {
              op: {
                type: 'string',
                const: 'move',
              },
              from: {
                type: 'string',
              },
              path: {
                type: 'string',
              },
            },
            required: ['op', 'from', 'path'],
          },
          {
            type: 'object',
            properties: {
              op: {
                type: 'string',
                const: 'copy',
              },
              from: {
                type: 'string',
              },
              path: {
                type: 'string',
              },
            },
            required: ['op', 'from', 'path'],
          },
          {
            type: 'object',
            properties: {
              op: {
                type: 'string',
                const: 'test',
              },
              path: {
                type: 'string',
              },
              value: {},
            },
            required: ['op', 'path', 'value'],
          },
        ],
      },
    },
    clientSchema: {
      type: 'object',
      properties: {
        nodes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'string',
              },
              template: {
                type: 'string',
              },
              config: {
                type: 'object',
                propertyNames: {
                  type: 'string',
                },
                additionalProperties: {},
              },
            },
            required: ['id', 'template', 'config'],
          },
        },
        edges: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              from: {
                type: 'string',
              },
              to: {
                type: 'string',
              },
              label: {
                type: 'string',
              },
            },
            required: ['from', 'to'],
          },
        },
      },
      required: ['nodes'],
    },
    newSchema: {
      type: 'object',
      properties: {
        nodes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'string',
              },
              template: {
                type: 'string',
              },
              config: {
                type: 'object',
                propertyNames: {
                  type: 'string',
                },
                additionalProperties: {},
              },
            },
            required: ['id', 'template', 'config'],
          },
        },
        edges: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              from: {
                type: 'string',
              },
              to: {
                type: 'string',
              },
              label: {
                type: 'string',
              },
            },
            required: ['from', 'to'],
          },
        },
      },
      required: ['nodes'],
    },
    status: {
      type: 'string',
      enum: ['pending', 'applying', 'applied', 'failed'],
    },
    error: {
      type: 'string',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
      pattern:
        '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
      pattern:
        '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
    },
  },
  required: [
    'id',
    'graphId',
    'baseVersion',
    'toVersion',
    'configurationDiff',
    'clientSchema',
    'newSchema',
    'status',
    'createdAt',
    'updatedAt',
  ],
} as const;

export const TemplateDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    description: {
      type: 'string',
    },
    kind: {
      type: 'string',
      enum: ['runtime', 'tool', 'simpleAgent', 'trigger', 'resource'],
    },
    schema: {
      type: 'object',
      propertyNames: {
        type: 'string',
      },
      additionalProperties: {},
    },
    inputs: {
      type: 'array',
      items: {
        anyOf: [
          {
            type: 'object',
            properties: {
              type: {
                type: 'string',
                const: 'kind',
              },
              value: {
                type: 'string',
                enum: ['runtime', 'tool', 'simpleAgent', 'trigger', 'resource'],
              },
              required: {
                type: 'boolean',
              },
              multiple: {
                type: 'boolean',
              },
            },
            required: ['type', 'value', 'multiple'],
          },
          {
            type: 'object',
            properties: {
              type: {
                type: 'string',
                const: 'template',
              },
              value: {
                type: 'string',
              },
              required: {
                type: 'boolean',
              },
              multiple: {
                type: 'boolean',
              },
            },
            required: ['type', 'value', 'multiple'],
          },
        ],
      },
    },
    outputs: {
      type: 'array',
      items: {
        anyOf: [
          {
            type: 'object',
            properties: {
              type: {
                type: 'string',
                const: 'kind',
              },
              value: {
                type: 'string',
                enum: ['runtime', 'tool', 'simpleAgent', 'trigger', 'resource'],
              },
              required: {
                type: 'boolean',
              },
              multiple: {
                type: 'boolean',
              },
            },
            required: ['type', 'value', 'multiple'],
          },
          {
            type: 'object',
            properties: {
              type: {
                type: 'string',
                const: 'template',
              },
              value: {
                type: 'string',
              },
              required: {
                type: 'boolean',
              },
              multiple: {
                type: 'boolean',
              },
            },
            required: ['type', 'value', 'multiple'],
          },
        ],
      },
    },
  },
  required: ['name', 'description', 'kind', 'schema'],
} as const;

export const ThreadDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
      pattern:
        '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
    },
    graphId: {
      type: 'string',
      format: 'uuid',
      pattern:
        '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
    },
    externalThreadId: {
      type: 'string',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
      pattern:
        '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
      pattern:
        '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
    },
    metadata: {
      anyOf: [
        {
          type: 'object',
          propertyNames: {
            type: 'string',
          },
          additionalProperties: {},
        },
        {
          type: 'null',
        },
      ],
    },
    source: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
    },
    status: {
      type: 'string',
      enum: ['running', 'done', 'need_more_info', 'stopped'],
    },
  },
  required: [
    'id',
    'graphId',
    'externalThreadId',
    'createdAt',
    'updatedAt',
    'status',
  ],
} as const;

export const ThreadMessageDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
      pattern:
        '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
    },
    threadId: {
      type: 'string',
      format: 'uuid',
      pattern:
        '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
    },
    nodeId: {
      type: 'string',
    },
    externalThreadId: {
      type: 'string',
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
      pattern:
        '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
      pattern:
        '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
    },
    message: {
      anyOf: [
        {
          type: 'object',
          properties: {
            role: {
              type: 'string',
              const: 'human',
            },
            content: {
              type: 'string',
            },
            additionalKwargs: {
              type: 'object',
              propertyNames: {
                type: 'string',
              },
              additionalProperties: {},
            },
          },
          required: ['role', 'content'],
        },
        {
          type: 'object',
          properties: {
            role: {
              type: 'string',
              const: 'ai',
            },
            content: {
              type: 'string',
            },
            id: {
              type: 'string',
            },
            toolCalls: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  name: {
                    type: 'string',
                  },
                  args: {
                    type: 'object',
                    propertyNames: {
                      type: 'string',
                    },
                    additionalProperties: {},
                  },
                  type: {
                    type: 'string',
                  },
                  id: {
                    type: 'string',
                  },
                },
                required: ['name', 'args', 'type', 'id'],
              },
            },
            additionalKwargs: {
              type: 'object',
              propertyNames: {
                type: 'string',
              },
              additionalProperties: {},
            },
          },
          required: ['role', 'content'],
        },
        {
          type: 'object',
          properties: {
            role: {
              type: 'string',
              const: 'system',
            },
            content: {
              type: 'string',
            },
            additionalKwargs: {
              type: 'object',
              propertyNames: {
                type: 'string',
              },
              additionalProperties: {},
            },
          },
          required: ['role', 'content'],
        },
        {
          type: 'object',
          properties: {
            role: {
              type: 'string',
              const: 'tool-shell',
            },
            name: {
              type: 'string',
              const: 'shell',
            },
            content: {
              type: 'object',
              properties: {
                exitCode: {
                  type: 'number',
                },
                stdout: {
                  type: 'string',
                },
                stderr: {
                  type: 'string',
                },
              },
              required: ['exitCode', 'stdout', 'stderr'],
            },
            toolCallId: {
              type: 'string',
            },
            additionalKwargs: {
              type: 'object',
              propertyNames: {
                type: 'string',
              },
              additionalProperties: {},
            },
          },
          required: ['role', 'name', 'content', 'toolCallId'],
        },
        {
          type: 'object',
          properties: {
            role: {
              type: 'string',
              const: 'tool',
            },
            name: {
              type: 'string',
            },
            content: {
              type: 'object',
              propertyNames: {
                type: 'string',
              },
              additionalProperties: {},
            },
            toolCallId: {
              type: 'string',
            },
            additionalKwargs: {
              type: 'object',
              propertyNames: {
                type: 'string',
              },
              additionalProperties: {},
            },
          },
          required: ['role', 'name', 'content', 'toolCallId'],
        },
      ],
    },
  },
  required: [
    'id',
    'threadId',
    'nodeId',
    'externalThreadId',
    'createdAt',
    'updatedAt',
    'message',
  ],
} as const;
