// This file is auto-generated by @hey-api/openapi-ts

export const HealthCheckResponseDtoSchema = {
  type: 'object',
  properties: {
    status: {
      type: 'string',
    },
    version: {
      type: 'string',
    },
  },
  required: ['status', 'version'],
} as const;
