// This file is auto-generated by @hey-api/openapi-ts

export const CreateGraphDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    description: {
      type: 'string',
      nullable: true,
    },
    version: {
      type: 'string',
    },
    schema: {
      type: 'object',
      properties: {
        nodes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'string',
              },
              template: {
                type: 'string',
              },
              config: {
                type: 'object',
                propertyNames: {
                  type: 'string',
                },
                additionalProperties: {},
              },
            },
            required: ['id', 'template', 'config'],
          },
        },
        edges: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              from: {
                type: 'string',
              },
              to: {
                type: 'string',
              },
              label: {
                type: 'string',
              },
            },
            required: ['from', 'to'],
          },
        },
        metadata: {
          type: 'object',
          properties: {
            graphId: {
              type: 'string',
            },
            name: {
              type: 'string',
            },
            version: {
              type: 'string',
            },
          },
          required: ['graphId', 'version'],
        },
      },
      required: ['nodes', 'metadata'],
    },
    metadata: {
      type: 'object',
      properties: {
        nodes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'string',
              },
              template: {
                type: 'string',
              },
              config: {
                type: 'object',
                propertyNames: {
                  type: 'string',
                },
                additionalProperties: {},
              },
            },
            required: ['id', 'template', 'config'],
          },
        },
        edges: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              from: {
                type: 'string',
              },
              to: {
                type: 'string',
              },
              label: {
                type: 'string',
              },
            },
            required: ['from', 'to'],
          },
        },
      },
      required: ['nodes'],
    },
  },
  required: ['name', 'version', 'schema', 'metadata'],
} as const;

export const GraphDtoSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
      pattern:
        '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
    },
    name: {
      type: 'string',
    },
    description: {
      type: 'string',
      nullable: true,
    },
    error: {
      type: 'string',
      nullable: true,
    },
    version: {
      type: 'string',
    },
    schema: {
      type: 'object',
      properties: {
        nodes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'string',
              },
              template: {
                type: 'string',
              },
              config: {
                type: 'object',
                propertyNames: {
                  type: 'string',
                },
                additionalProperties: {},
              },
            },
            required: ['id', 'template', 'config'],
          },
        },
        edges: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              from: {
                type: 'string',
              },
              to: {
                type: 'string',
              },
              label: {
                type: 'string',
              },
            },
            required: ['from', 'to'],
          },
        },
        metadata: {
          type: 'object',
          properties: {
            graphId: {
              type: 'string',
            },
            name: {
              type: 'string',
            },
            version: {
              type: 'string',
            },
          },
          required: ['graphId', 'version'],
        },
      },
      required: ['nodes', 'metadata'],
    },
    status: {
      type: 'string',
      enum: ['created', 'running', 'stopped', 'error'],
    },
    metadata: {
      type: 'object',
      propertyNames: {
        type: 'string',
      },
      additionalProperties: {},
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
      pattern:
        '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
      pattern:
        '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$',
    },
  },
  required: [
    'id',
    'name',
    'version',
    'schema',
    'status',
    'createdAt',
    'updatedAt',
  ],
} as const;

export const UpdateGraphDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    description: {
      type: 'string',
      nullable: true,
    },
    version: {
      type: 'string',
    },
    schema: {
      type: 'object',
      properties: {
        nodes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'string',
              },
              template: {
                type: 'string',
              },
              config: {
                type: 'object',
                propertyNames: {
                  type: 'string',
                },
                additionalProperties: {},
              },
            },
            required: ['id', 'template', 'config'],
          },
        },
        edges: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              from: {
                type: 'string',
              },
              to: {
                type: 'string',
              },
              label: {
                type: 'string',
              },
            },
            required: ['from', 'to'],
          },
        },
        metadata: {
          type: 'object',
          properties: {
            graphId: {
              type: 'string',
            },
            name: {
              type: 'string',
            },
            version: {
              type: 'string',
            },
          },
          required: ['graphId', 'version'],
        },
      },
      required: ['nodes', 'metadata'],
    },
    metadata: {
      type: 'object',
      properties: {
        nodes: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'string',
              },
              template: {
                type: 'string',
              },
              config: {
                type: 'object',
                propertyNames: {
                  type: 'string',
                },
                additionalProperties: {},
              },
            },
            required: ['id', 'template', 'config'],
          },
        },
        edges: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              from: {
                type: 'string',
              },
              to: {
                type: 'string',
              },
              label: {
                type: 'string',
              },
            },
            required: ['from', 'to'],
          },
        },
      },
      required: ['nodes'],
    },
  },
} as const;

export const TemplateDtoSchema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
    },
    description: {
      type: 'string',
    },
    kind: {
      type: 'string',
      enum: ['runtime', 'tool', 'simpleAgent', 'trigger'],
    },
    schema: {
      type: 'object',
      propertyNames: {
        type: 'string',
      },
      additionalProperties: {},
    },
  },
  required: ['name', 'description', 'kind', 'schema'],
} as const;
