// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type {
  Client,
  Options as Options2,
  TDataShape,
} from './client/index.js';
import type {
  AnalyzeThreadData,
  AnalyzeThreadResponses,
  CreateDocData,
  CreateDocResponses,
  CreateGraphData,
  CreateGraphResponses,
  DeleteDocData,
  DeleteDocResponses,
  DeleteGraphData,
  DeleteGraphResponses,
  DeleteThreadData,
  DeleteThreadResponses,
  DestroyGraphData,
  DestroyGraphResponses,
  ExecuteTriggerData,
  ExecuteTriggerResponses,
  FindGraphByIdData,
  FindGraphByIdResponses,
  GetAllGraphsData,
  GetAllGraphsResponses,
  GetAllTemplatesData,
  GetAllTemplatesResponses,
  GetCompiledNodesData,
  GetCompiledNodesResponses,
  GetDocChunksData,
  GetDocChunksResponses,
  GetDocData,
  GetDocResponses,
  GetGraphRevisionData,
  GetGraphRevisionResponses,
  GetGraphRevisionsData,
  GetGraphRevisionsResponses,
  GetThreadByExternalIdData,
  GetThreadByExternalIdResponses,
  GetThreadByIdData,
  GetThreadByIdResponses,
  GetThreadMessagesData,
  GetThreadMessagesResponses,
  GetThreadsData,
  GetThreadsResponses,
  GetThreadUsageStatisticsData,
  GetThreadUsageStatisticsResponses,
  ListDocsData,
  ListDocsResponses,
  ListModelsData,
  ListModelsResponses,
  RunGraphData,
  RunGraphResponses,
  StopThreadByExternalIdData,
  StopThreadByExternalIdResponses,
  StopThreadData,
  StopThreadResponses,
  SuggestAgentInstructionsData,
  SuggestAgentInstructionsResponses,
  UpdateDocData,
  UpdateDocResponses,
  UpdateGraphData,
  UpdateGraphResponses,
} from './types.gen.js';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const listModels = <ThrowOnError extends boolean = false>(
  options?: Options<ListModelsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListModelsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/litellm/models',
    ...options,
  });

export const listDocs = <ThrowOnError extends boolean = false>(
  options?: Options<ListDocsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListDocsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/knowledge-docs',
    ...options,
  });

export const createDoc = <ThrowOnError extends boolean = false>(
  options: Options<CreateDocData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateDocResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/knowledge-docs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteDoc = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDocData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteDocResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/knowledge-docs/{id}',
    ...options,
  });

export const getDoc = <ThrowOnError extends boolean = false>(
  options: Options<GetDocData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetDocResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/knowledge-docs/{id}',
    ...options,
  });

export const updateDoc = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDocData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdateDocResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/knowledge-docs/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getDocChunks = <ThrowOnError extends boolean = false>(
  options: Options<GetDocChunksData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetDocChunksResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/knowledge-docs/{id}/chunks',
    ...options,
  });

export const suggestAgentInstructions = <ThrowOnError extends boolean = false>(
  options: Options<SuggestAgentInstructionsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SuggestAgentInstructionsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/graphs/{graphId}/nodes/{nodeId}/suggest-instructions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const analyzeThread = <ThrowOnError extends boolean = false>(
  options: Options<AnalyzeThreadData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AnalyzeThreadResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/threads/{threadId}/analyze',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getAllGraphs = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllGraphsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetAllGraphsResponses, unknown, ThrowOnError>(
    {
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/graphs',
      ...options,
    },
  );

export const createGraph = <ThrowOnError extends boolean = false>(
  options: Options<CreateGraphData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateGraphResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/graphs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteGraph = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGraphData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteGraphResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/graphs/{id}',
    ...options,
  });

export const findGraphById = <ThrowOnError extends boolean = false>(
  options: Options<FindGraphByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<FindGraphByIdResponses, unknown, ThrowOnError>(
    {
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/graphs/{id}',
      ...options,
    },
  );

export const updateGraph = <ThrowOnError extends boolean = false>(
  options: Options<UpdateGraphData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdateGraphResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/graphs/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getCompiledNodes = <ThrowOnError extends boolean = false>(
  options: Options<GetCompiledNodesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCompiledNodesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/graphs/{id}/nodes',
    ...options,
  });

export const runGraph = <ThrowOnError extends boolean = false>(
  options: Options<RunGraphData, ThrowOnError>,
) =>
  (options.client ?? client).post<RunGraphResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/graphs/{id}/run',
    ...options,
  });

export const destroyGraph = <ThrowOnError extends boolean = false>(
  options: Options<DestroyGraphData, ThrowOnError>,
) =>
  (options.client ?? client).post<DestroyGraphResponses, unknown, ThrowOnError>(
    {
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/graphs/{id}/destroy',
      ...options,
    },
  );

export const executeTrigger = <ThrowOnError extends boolean = false>(
  options: Options<ExecuteTriggerData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ExecuteTriggerResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/graphs/{graphId}/triggers/{triggerId}/execute',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getGraphRevisions = <ThrowOnError extends boolean = false>(
  options: Options<GetGraphRevisionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetGraphRevisionsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/graphs/{graphId}/revisions',
    ...options,
  });

export const getGraphRevision = <ThrowOnError extends boolean = false>(
  options: Options<GetGraphRevisionData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetGraphRevisionResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/graphs/{graphId}/revisions/{id}',
    ...options,
  });

export const getAllTemplates = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllTemplatesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllTemplatesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/templates',
    ...options,
  });

export const getThreads = <ThrowOnError extends boolean = false>(
  options?: Options<GetThreadsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetThreadsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/threads',
    ...options,
  });

export const deleteThread = <ThrowOnError extends boolean = false>(
  options: Options<DeleteThreadData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteThreadResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/threads/{threadId}',
    ...options,
  });

export const getThreadById = <ThrowOnError extends boolean = false>(
  options: Options<GetThreadByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetThreadByIdResponses, unknown, ThrowOnError>(
    {
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/api/v1/threads/{threadId}',
      ...options,
    },
  );

export const getThreadByExternalId = <ThrowOnError extends boolean = false>(
  options: Options<GetThreadByExternalIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetThreadByExternalIdResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/threads/external/{externalThreadId}',
    ...options,
  });

export const getThreadMessages = <ThrowOnError extends boolean = false>(
  options: Options<GetThreadMessagesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetThreadMessagesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/threads/{threadId}/messages',
    ...options,
  });

export const getThreadUsageStatistics = <ThrowOnError extends boolean = false>(
  options: Options<GetThreadUsageStatisticsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetThreadUsageStatisticsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/threads/{threadId}/usage-statistics',
    ...options,
  });

export const stopThread = <ThrowOnError extends boolean = false>(
  options: Options<StopThreadData, ThrowOnError>,
) =>
  (options.client ?? client).post<StopThreadResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/threads/{threadId}/stop',
    ...options,
  });

export const stopThreadByExternalId = <ThrowOnError extends boolean = false>(
  options: Options<StopThreadByExternalIdData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StopThreadByExternalIdResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/threads/external/{externalThreadId}/stop',
    ...options,
  });
