import { AlertTriangle } from 'lucide-react';
import React from 'react';

import type { ThreadDtoStatusEnum } from '../../../autogenerated/api';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '../../../components/ui/popover';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '../../../components/ui/tooltip';
import { formatDurationMs } from '../../graphs/components/threadMessages/threadMessagesViewUtils';
import { useLiveThreadDuration } from '../hooks/useLiveThreadDuration';
import type { ThreadTokenUsageSnapshot } from '../types';
import {
  clampPercent,
  formatCompactNumber,
  formatUsd,
} from '../utils/chatsPageUtils';
import { ContextUsageGauge } from './ContextUsageGauge';

type ThreadTokenUsageLineUsage = ThreadTokenUsageSnapshot & {
  effectiveCostLimitUsd?: number | null;
  stopReason?: string | null;
};

export const ThreadTokenUsageLine: React.FC<{
  usage?: ThreadTokenUsageLineUsage | null;
  withPopover?: boolean;
  contextMaxTokens?: number;
  contextPercent?: number;
  runningStartedAt?: string | null;
  totalRunningMs?: number;
  threadStatus?: ThreadDtoStatusEnum | string;
}> = ({
  usage,
  withPopover = false,
  contextMaxTokens,
  contextPercent,
  runningStartedAt,
  totalRunningMs,
  threadStatus,
}) => {
  const totalTokens = usage?.totalTokens;
  const totalPrice = usage?.totalPrice;
  const currentContext = usage?.currentContext;
  const effectiveCostLimitUsd = usage?.effectiveCostLimitUsd;
  const stopReason = usage?.stopReason;

  // Show the duration suffix only when real timer data is present.
  // Gating on threadStatus alone (without time fields) would render " · —"
  // when no timer data exists, which looks like broken/missing data.
  const showDuration =
    (runningStartedAt != null && threadStatus !== undefined) ||
    (typeof totalRunningMs === 'number' && totalRunningMs > 0);

  const liveDurationMs = useLiveThreadDuration({
    runningStartedAt,
    totalRunningMs,
    status: threadStatus,
  });

  if (typeof totalTokens !== 'number') {
    return null;
  }

  const percent =
    typeof contextPercent === 'number'
      ? contextPercent
      : typeof currentContext === 'number' &&
          typeof contextMaxTokens === 'number' &&
          Number.isFinite(contextMaxTokens) &&
          contextMaxTokens > 0
        ? (currentContext / contextMaxTokens) * 100
        : undefined;

  const hasLimit =
    typeof effectiveCostLimitUsd === 'number' &&
    Number.isFinite(effectiveCostLimitUsd);
  const costLimitReached = stopReason === 'cost_limit';

  const costText = hasLimit
    ? `${formatUsd(totalPrice)} / ${formatUsd(effectiveCostLimitUsd)}`
    : formatUsd(totalPrice);

  const durationSuffix = showDuration
    ? ` · ${formatDurationMs(liveDurationMs)}`
    : '';

  const labelText = `Token usage: ${formatCompactNumber(totalTokens)} (${costText})${durationSuffix}`;

  // H4: 14px bold qualifies as large text (WCAG AA threshold 3:1, met by
  // text-destructive). AlertTriangle ensures color is not the sole signal.
  const labelSpan = costLimitReached ? (
    <span
      className="text-sm font-semibold text-destructive inline-flex items-center gap-1"
      role="status">
      <AlertTriangle className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />
      {labelText} — Cost limit reached
    </span>
  ) : (
    <span className="text-xs text-muted-foreground">{labelText}</span>
  );

  const labelNode = costLimitReached ? (
    <Tooltip>
      <TooltipTrigger asChild>
        <span className="inline-block cursor-help">{labelSpan}</span>
      </TooltipTrigger>
      <TooltipContent>Raise the limit to resume.</TooltipContent>
    </Tooltip>
  ) : (
    labelSpan
  );

  const line = (
    <span className="inline-flex items-center gap-2">
      {labelNode}
      {typeof percent === 'number' && <ContextUsageGauge percent={percent} />}
    </span>
  );

  if (!withPopover) {
    return line;
  }

  const fmt = (n?: number) =>
    typeof n === 'number' ? n.toLocaleString() : '\u2014';

  const popoverContent = (
    <div className="w-64 space-y-1">
      <p className="font-semibold text-foreground text-xs mb-2">Token Usage</p>
      <div className="flex justify-between text-xs text-muted-foreground">
        <span>Input</span>
        <span className="font-medium text-foreground">
          {fmt(usage?.inputTokens)}
        </span>
      </div>
      {typeof usage?.cachedInputTokens === 'number' && (
        <div className="flex justify-between text-xs text-muted-foreground">
          <span>Cached input</span>
          <span className="font-medium text-foreground">
            {fmt(usage.cachedInputTokens)}
          </span>
        </div>
      )}
      <div className="flex justify-between text-xs text-muted-foreground">
        <span>Output</span>
        <span className="font-medium text-foreground">
          {fmt(usage?.outputTokens)}
        </span>
      </div>
      {typeof usage?.reasoningTokens === 'number' &&
        usage.reasoningTokens > 0 && (
          <div className="flex justify-between text-xs text-muted-foreground">
            <span>Reasoning</span>
            <span className="font-medium text-foreground">
              {fmt(usage.reasoningTokens)}
            </span>
          </div>
        )}
      {typeof usage?.currentContext === 'number' && (
        <div className="flex justify-between text-xs text-muted-foreground">
          <span>Current context</span>
          <span className="font-medium text-foreground">
            {fmt(usage.currentContext)}
          </span>
        </div>
      )}
      <div className="border-t border-border my-1" />
      <div className="flex justify-between text-xs text-muted-foreground">
        <span>Total</span>
        <span className="font-semibold text-foreground">
          {fmt(usage?.totalTokens)}
        </span>
      </div>
      <div className="flex justify-between text-xs text-muted-foreground">
        <span>Cost</span>
        <span className="font-semibold text-foreground">
          {formatUsd(usage?.totalPrice)}
        </span>
      </div>
      {hasLimit && (
        <div className="flex justify-between text-xs text-muted-foreground">
          <span>Cost limit</span>
          <span className="font-semibold text-foreground">
            {formatUsd(effectiveCostLimitUsd)}
          </span>
        </div>
      )}
      {typeof percent === 'number' && (
        <div className="flex justify-between text-xs text-muted-foreground">
          <span>Context usage</span>
          <span className="font-medium text-foreground">
            {Math.round(clampPercent(percent))}%
            {typeof contextMaxTokens === 'number' &&
              Number.isFinite(contextMaxTokens) &&
              contextMaxTokens > 0 && (
                <> ({formatCompactNumber(contextMaxTokens)})</>
              )}
          </span>
        </div>
      )}
    </div>
  );

  return (
    <Popover>
      <PopoverTrigger asChild>
        <span className="inline-block cursor-help">{line}</span>
      </PopoverTrigger>
      <PopoverContent side="bottom" align="start" className="w-auto p-3">
        {popoverContent}
      </PopoverContent>
    </Popover>
  );
};
