import { basename } from 'node:path';

import { ToolRunnableConfig } from '@langchain/core/tools';
import { Injectable } from '@nestjs/common';
import dedent from 'dedent';
import { isObject } from 'lodash';
import { z } from 'zod';

import { BaseAgentConfigurable } from '../../../../agents/services/nodes/base-node';
import {
  ExtendedLangGraphRunnableConfig,
  ToolInvokeResult,
} from '../../base-tool';
import { FilesBaseTool, FilesBaseToolConfig } from './files-base.tool';

const MAX_MATCHES = 30;

export const FilesSearchTextToolSchema = z.object({
  dir: z
    .string()
    .min(1)
    .optional()
    .describe(
      'Directory path to search. If omitted, uses the current working directory of the persistent shell session. Use absolute paths when provided.',
    ),
  query: z
    .string()
    .min(1)
    .describe('The text pattern to search for (regex supported by ripgrep).'),
  filePath: z
    .string()
    .optional()
    .describe(
      'Optional absolute file path to search in. If provided, searches only in this specific file. Can be used directly with paths returned from files_find_paths.',
    ),
  includeGlobs: z
    .array(z.string())
    .optional()
    .describe(
      'Optional array of glob patterns to include (e.g., ["*.ts", "src/**"]).',
    ),
  excludeGlobs: z
    .array(z.string())
    .optional()
    .describe(
      'Optional array of glob patterns to exclude (e.g., ["*.test.ts", "node_modules/**"]).',
    ),
});

export type FilesSearchTextToolSchemaType = z.infer<
  typeof FilesSearchTextToolSchema
>;

type FilesSearchTextToolOutput = {
  error?: string;
  matches?: {
    type: string;
    data: {
      path?: {
        text: string;
      };
      lines?: {
        text: string;
      };
      line_number?: number;
      absolute_offset?: number;
      submatches?: {
        match: {
          text: string;
        };
        start: number;
        end: number;
      }[];
    };
  }[];
};

function shQuote(s: string) {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

@Injectable()
export class FilesSearchTextTool extends FilesBaseTool<FilesSearchTextToolSchemaType> {
  public name = 'files_search_text';
  public description =
    'Search file contents with ripgrep (regex) and return structured matches.';

  protected override generateTitle(
    args: FilesSearchTextToolSchemaType,
    _config: FilesBaseToolConfig,
  ): string {
    const location = args.filePath
      ? basename(args.filePath)
      : (args.dir ?? 'current directory');
    return `Searching in ${location}`;
  }

  public getDetailedInstructions(
    _config: FilesBaseToolConfig,
    _lgConfig?: ExtendedLangGraphRunnableConfig,
  ): string {
    return dedent`
      ### Overview
      Searches text patterns across files using ripgrep. Returns JSON with file paths, line numbers, matches. If \`dir\` omitted, searches in current shell cwd. Supports regex.

      ### When to Use
      Finding function/class/variable definitions or usages, specific patterns (TODO, errors), config values, imports, feature implementations.

      ### When NOT to Use
      When exact file known → use files_read. For listing files → use files_find_paths. For symbol search → use files_search_tags if available.

      ### Best Practices
      Be specific with patterns. Use file filters (includeGlobs/excludeGlobs) to reduce noise. Escape special regex chars. For type/enum discovery: search "(enum|type|interface)\\\\s+TypeName" first, then field definitions if not found.

      ### Default excludes
      Auto-excludes (when excludeGlobs NOT provided): .git, node_modules, dist, build, coverage, .next, .turbo, .vercel, .cache, out, .output, tmp, temp, src/autogenerated. If you provide excludeGlobs, defaults NOT applied (include them explicitly if needed, plus repo-specific like generated/, vendor/, target/).

      ### Examples
      **1. Literal search:**
      \`\`\`json
      {"dir": "/repo", "query": "getUserById"}
      \`\`\`

      **2. Regex search for function definitions:**
      \`\`\`json
      {"dir": "/repo", "query": "function\\\\s+handleSubmit|const\\\\s+handleSubmit"}
      \`\`\`

      **3. Case-insensitive search:**
      \`\`\`json
      {"query": "(?i)error", "includeGlobs": ["*.ts"]}
      \`\`\`

      **4. Find React hooks in specific files:**
      \`\`\`json
      {"dir": "/repo/src", "query": "use(State|Effect|Ref)\\\\(", "includeGlobs": ["*.tsx"], "excludeGlobs": ["*.test.tsx"]}
      \`\`\`

      **5. Find type/enum definitions:**
      \`\`\`json
      {"query": "(enum|type|interface)\\\\s+UserRole"}
      \`\`\`

      ### Results
      Returns up to 30 matches. Empty array if no matches. Use files_read with line ranges to see context around matches.
    `;
  }

  public get schema() {
    return z.toJSONSchema(FilesSearchTextToolSchema, {
      target: 'draft-7',
      reused: 'ref',
    });
  }

  public async invoke(
    args: FilesSearchTextToolSchemaType,
    config: FilesBaseToolConfig,
    cfg: ToolRunnableConfig<BaseAgentConfigurable>,
  ): Promise<ToolInvokeResult<FilesSearchTextToolOutput>> {
    const title = this.generateTitle?.(args, config);
    const messageMetadata = { __title: title };
    const cmdParts: string[] = ['rg', '--json'];

    if (args.filePath) {
      cmdParts.push('--', shQuote(args.query), shQuote(args.filePath));
    } else {
      cmdParts.push('--hidden');

      const defaultExcludes = [
        '.git',
        'node_modules',
        '.next',
        'dist',
        'build',
        'coverage',
        '.turbo',
        '.vercel',
        '.cache',
        'out',
        '.output',
        'tmp',
        'temp',
        'src/autogenerated',
      ];

      if (args.includeGlobs && args.includeGlobs.length > 0) {
        for (const glob of args.includeGlobs) {
          cmdParts.push('--glob', shQuote(glob));
        }
      }

      if (args.excludeGlobs && args.excludeGlobs.length > 0) {
        for (const glob of args.excludeGlobs) {
          cmdParts.push('--glob', shQuote(`!${glob}`));
        }
      } else {
        for (const glob of defaultExcludes) {
          cmdParts.push('--glob', shQuote(`!${glob}/**`));
        }
      }

      cmdParts.push('--', shQuote(args.query), '.');
    }

    const baseCmd = cmdParts.join(' ');
    const cmd = args.dir ? `cd ${shQuote(args.dir)} && ${baseCmd}` : baseCmd;

    const res = await this.execCommand(
      {
        cmd,
      },
      config,
      cfg,
    );

    if (res.exitCode !== 0) {
      if (res.exitCode === 1 && !res.stderr) {
        return {
          output: {
            matches: [],
          },
          messageMetadata,
        };
      }

      return {
        output: {
          error: res.stderr || res.stdout || 'Failed to search text',
        },
        messageMetadata,
      };
    }

    const lines = res.stdout
      .split('\n')
      .filter((line) => line.trim().length > 0);
    const matches: FilesSearchTextToolOutput['matches'] = [];
    type Match = NonNullable<FilesSearchTextToolOutput['matches']>[number];

    for (const line of lines) {
      try {
        const parsed = JSON.parse(line) as unknown;
        const parsedType = isObject(parsed)
          ? (parsed as { type?: unknown }).type
          : undefined;

        if (parsedType === 'match') {
          if (matches.length >= MAX_MATCHES) {
            break;
          }
          matches.push(parsed as Match);
        }
      } catch {
        continue;
      }
    }

    return {
      output: {
        matches,
      },
      messageMetadata,
    };
  }
}
