import { basename } from 'node:path';

import { ToolRunnableConfig } from '@langchain/core/tools';
import { Injectable } from '@nestjs/common';
import dedent from 'dedent';
import { z } from 'zod';

import { BaseAgentConfigurable } from '../../../../agents/services/nodes/base-node';
import {
  ExtendedLangGraphRunnableConfig,
  ToolInvokeResult,
} from '../../base-tool';
import { FilesBaseTool, FilesBaseToolConfig } from './files-base.tool';

export const FilesDeleteToolSchema = z.object({
  filePath: z
    .string()
    .min(1)
    .describe(
      'Absolute path to the file to delete. Must point to a file, not a directory. Verify the path with files_find_paths or files_read before deleting.',
    ),
});

export type FilesDeleteToolSchemaType = z.infer<typeof FilesDeleteToolSchema>;

type FilesDeleteToolOutput = {
  success?: boolean;
  error?: string;
};

@Injectable()
export class FilesDeleteTool extends FilesBaseTool<FilesDeleteToolSchemaType> {
  public name = 'files_delete';
  public description =
    'Permanently delete a single file by absolute path. This operation is destructive and cannot be undone. Only files are accepted — directories are rejected with an error. Before deleting, verify the path using files_find_paths or files_read to avoid accidental removal of the wrong file. Do not use this for editing content; use files_apply_changes instead.';

  protected override generateTitle(
    args: FilesDeleteToolSchemaType,
    _config: FilesBaseToolConfig,
  ): string {
    return `Deleting ${basename(args.filePath)}`;
  }

  public getDetailedInstructions(
    _config: FilesBaseToolConfig,
    _lgConfig?: ExtendedLangGraphRunnableConfig,
  ): string {
    return dedent`
      ### Overview
      Permanently delete a single file by absolute path. This operation is **destructive and cannot be undone** — there is no trash/recycle bin. Only files are accepted; directories are rejected with an error.

      ### When to Use
      - Cleaning up generated, temporary, or intermediate files
      - Removing a file you just created that is no longer needed
      - Deleting obsolete files during a refactor (after confirming they are unused)

      ### When NOT to Use
      - Deleting directories → not supported (use shell \`rm -rf\` with caution)
      - Editing or modifying file content → use \`files_apply_changes\` or \`files_edit\`
      - Removing multiple files at once → call this tool once per file

      ### Best Practices
      - **Always verify the path** with \`files_find_paths\` or \`files_read\` before deleting to avoid accidental removal
      - Avoid deleting shared project files unless you created them or confirmed they are unused
      - If the repository is under version control, deleted files can be recovered via \`git checkout\` — but this tool does not interact with git
      - Prefer not deleting files that might be needed later; leave cleanup to the user when in doubt

      ### Error Cases
      - "File not found" — the path does not exist; verify with \`files_find_paths\`
      - "Path is a directory" — directories cannot be deleted with this tool; use shell instead

      ### Examples
      **1. Delete a temp file:**
      \`\`\`json
      {"filePath":"/repo/tmp/debug.log"}
      \`\`\`

      **2. Delete an obsolete generated file:**
      \`\`\`json
      {"filePath":"/repo/src/autogenerated/old-schema.ts"}
      \`\`\`
    `;
  }

  public get schema() {
    return FilesDeleteToolSchema;
  }

  public async invoke(
    args: FilesDeleteToolSchemaType,
    config: FilesBaseToolConfig,
    cfg: ToolRunnableConfig<BaseAgentConfigurable>,
  ): Promise<ToolInvokeResult<FilesDeleteToolOutput>> {
    const title = this.generateTitle?.(args, config);
    const messageMetadata = { __title: title };
    const fullFilePath = args.filePath;
    const cmd = [
      `if [ ! -e "${fullFilePath}" ]; then`,
      '  echo "File not found" >&2;',
      '  exit 1;',
      'fi;',
      `if [ -d "${fullFilePath}" ]; then`,
      '  echo "Path is a directory; only files can be deleted" >&2;',
      '  exit 1;',
      'fi;',
      `rm -f "${fullFilePath}"`,
    ].join(' ');

    const res = await this.execCommand(
      {
        cmd,
      },
      config,
      cfg,
    );

    if (res.exitCode !== 0) {
      return {
        output: {
          success: false,
          error: res.stderr || res.stdout || 'Failed to delete file',
        },
        messageMetadata,
      };
    }

    return {
      output: {
        success: true,
      },
      messageMetadata,
    };
  }
}
