import type { ThreadMessageDto } from '../../../autogenerated';

export interface ContentBlock {
  type: 'text' | 'image_url';
  text?: string;
  image_url?: { url: string; detail?: 'auto' | 'low' | 'high' };
}

export type MessageAdditionalKwargs = Record<string, unknown> & {
  __runId?: string;
  __threadId?: string;
  __createdAt?: string;
  __model?: string;
  __title?: string;

  // Used by message transformer for reasoning + LLM visibility controls
  __reasoningId?: string;
  __hideForLlm?: boolean;
  __hideForSummary?: boolean;
  __isAgentInstructionMessage?: boolean;
  __isReportingMessage?: boolean;

  __context?: unknown;

  // Subagent inner messages link back to parent tool call
  __toolCallId?: string;

  // Names of tools that were auto-loaded (deferred tool loading) when processing this tool call
  __loadedTools?: string[];
};

export interface PendingMessage {
  content: string | ContentBlock[];
  role: 'human' | 'ai';
  additionalKwargs?: MessageAdditionalKwargs;
  createdAt?: string;
}

export type MessageScopeKey = string | 'all';

export type MessagesState = Record<
  string,
  Record<MessageScopeKey, ThreadMessageDto[]>
>;

export type PendingMessagesState = Record<
  string,
  Record<MessageScopeKey, PendingMessage[]>
>;

export type MessagesUpdater = (
  threadId: string,
  updater: (prev: ThreadMessageDto[]) => ThreadMessageDto[],
  nodeId?: string,
) => void;

export type PendingMessagesUpdater = (
  threadId: string,
  updater: (prev: PendingMessage[]) => PendingMessage[],
  nodeId?: string,
) => void;
