/**
 * Synthetic storybook fixture data for thread cost playback scenarios.
 * Covers the test matrix from the cost-accounting rules:
 *   A — all priced, running→done
 *   B — mixed priced + unpriced
 *   C — all unpriced
 *
 * totalPrice is declared number | null in these fixtures because the
 * autogenerated ThreadMessageDtoRequestTokenUsage has `totalPrice?: number`
 * (optional, not nullable). Wave 3 OpenAPI regen will widen it to
 * `number | null`. Until then, each fixture object is cast to satisfy the
 * widened shape used by cost-aggregation consumers.
 *
 * // totalPrice: number | null until Wave 3 regen widens the autogenerated type
 */

import type { ThreadMessageDto } from '../../../autogenerated/api';

/** Widened token usage shape used across all fixtures. */
type FixtureTokenUsage = {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  // totalPrice: number | null until Wave 3 regen widens the autogenerated type
  totalPrice: number | null;
};

/** ThreadMessageDto with totalPrice widened to number | null. */
type FixtureMessage = Omit<
  ThreadMessageDto,
  'requestTokenUsage' | 'toolTokenUsage'
> & {
  requestTokenUsage?: FixtureTokenUsage | null;
  toolTokenUsage?: FixtureTokenUsage | null;
};

const RUN_ID_A = 'run-scenario-a';
const RUN_ID_B = 'run-scenario-b';
const RUN_ID_C = 'run-scenario-c';

// ---------------------------------------------------------------------------
// Scenario A — "All priced, running→done"
// 6 AI messages (prices: 0.015, 0.02, 0.035, 0.01, 0.025, 0.02 → sum $0.125)
// 2 interleaved tool call + tool result pairs.
// Final AI message signals run done via no pending tool calls.
// ---------------------------------------------------------------------------

export const scenarioAFixtures: FixtureMessage[] = [
  {
    id: 'a-msg-1',
    threadId: 'thread-a',
    nodeId: 'node-a',
    externalThreadId: 'ext-thread-a',
    createdAt: '2024-01-01T10:00:00.000Z',
    updatedAt: '2024-01-01T10:00:00.000Z',
    message: {
      role: 'ai',
      content: 'Starting task. Let me search for the relevant information.',
      runId: RUN_ID_A,
      toolCalls: [
        {
          id: 'tc-1',
          name: 'web_search',
          args: { query: 'React hooks patterns' },
          type: 'tool_call',
        },
      ],
    },
    requestTokenUsage: {
      inputTokens: 120,
      outputTokens: 45,
      totalTokens: 165,
      totalPrice: 0.015,
    },
  },
  {
    id: 'a-msg-2',
    threadId: 'thread-a',
    nodeId: 'node-a',
    externalThreadId: 'ext-thread-a',
    createdAt: '2024-01-01T10:00:01.000Z',
    updatedAt: '2024-01-01T10:00:01.000Z',
    message: {
      role: 'tool',
      name: 'web_search',
      content: { results: ['Result 1', 'Result 2'] },
      toolCallId: 'tc-1',
      runId: RUN_ID_A,
    },
    requestTokenUsage: null,
  },
  {
    id: 'a-msg-3',
    threadId: 'thread-a',
    nodeId: 'node-a',
    externalThreadId: 'ext-thread-a',
    createdAt: '2024-01-01T10:00:02.000Z',
    updatedAt: '2024-01-01T10:00:02.000Z',
    message: {
      role: 'ai',
      content: 'Found relevant results. Let me analyze them further.',
      runId: RUN_ID_A,
      toolCalls: [
        {
          id: 'tc-2',
          name: 'shell',
          args: { command: 'grep -r pattern src/' },
          type: 'tool_call',
        },
      ],
    },
    requestTokenUsage: {
      inputTokens: 200,
      outputTokens: 60,
      totalTokens: 260,
      totalPrice: 0.02,
    },
  },
  {
    id: 'a-msg-4',
    threadId: 'thread-a',
    nodeId: 'node-a',
    externalThreadId: 'ext-thread-a',
    createdAt: '2024-01-01T10:00:03.000Z',
    updatedAt: '2024-01-01T10:00:03.000Z',
    message: {
      role: 'tool',
      name: 'shell',
      content: { output: 'src/hooks/useCallback.ts:42: const memoized = ...' },
      toolCallId: 'tc-2',
      runId: RUN_ID_A,
    },
    requestTokenUsage: null,
  },
  {
    id: 'a-msg-5',
    threadId: 'thread-a',
    nodeId: 'node-a',
    externalThreadId: 'ext-thread-a',
    createdAt: '2024-01-01T10:00:04.000Z',
    updatedAt: '2024-01-01T10:00:04.000Z',
    message: {
      role: 'ai',
      content: 'Good. Now synthesizing results into a structured analysis.',
      runId: RUN_ID_A,
    },
    requestTokenUsage: {
      inputTokens: 380,
      outputTokens: 120,
      totalTokens: 500,
      totalPrice: 0.035,
    },
  },
  {
    id: 'a-msg-6',
    threadId: 'thread-a',
    nodeId: 'node-a',
    externalThreadId: 'ext-thread-a',
    createdAt: '2024-01-01T10:00:05.000Z',
    updatedAt: '2024-01-01T10:00:05.000Z',
    message: {
      role: 'ai',
      content: 'Analysis complete. Here are the key patterns found.',
      runId: RUN_ID_A,
    },
    requestTokenUsage: {
      inputTokens: 100,
      outputTokens: 40,
      totalTokens: 140,
      totalPrice: 0.01,
    },
  },
  {
    id: 'a-msg-7',
    threadId: 'thread-a',
    nodeId: 'node-a',
    externalThreadId: 'ext-thread-a',
    createdAt: '2024-01-01T10:00:06.000Z',
    updatedAt: '2024-01-01T10:00:06.000Z',
    message: {
      role: 'ai',
      content: 'Expanding on implementation details and best practices.',
      runId: RUN_ID_A,
    },
    requestTokenUsage: {
      inputTokens: 250,
      outputTokens: 95,
      totalTokens: 345,
      totalPrice: 0.025,
    },
  },
  {
    id: 'a-msg-8',
    threadId: 'thread-a',
    nodeId: 'node-a',
    externalThreadId: 'ext-thread-a',
    createdAt: '2024-01-01T10:00:07.000Z',
    updatedAt: '2024-01-01T10:00:07.000Z',
    message: {
      role: 'ai',
      // Final message — run is done
      content:
        'Task completed successfully. All patterns have been documented.',
      runId: RUN_ID_A,
    },
    requestTokenUsage: {
      inputTokens: 200,
      outputTokens: 80,
      totalTokens: 280,
      totalPrice: 0.02,
    },
  },
];

// ---------------------------------------------------------------------------
// Scenario B — "Mixed priced and unpriced"
// Outer agent messages: priced ($0.02, $0.03 → $0.05 known)
// Subagent-internal messages: totalPrice null (unpriced model)
//   marked with additionalKwargs.__hideForLlm: true per spec
// hasUnpricedCalls should be true for this scenario.
// ---------------------------------------------------------------------------

export const scenarioBFixtures: FixtureMessage[] = [
  {
    id: 'b-msg-1',
    threadId: 'thread-b',
    nodeId: 'node-b-outer',
    externalThreadId: 'ext-thread-b',
    createdAt: '2024-01-01T11:00:00.000Z',
    updatedAt: '2024-01-01T11:00:00.000Z',
    message: {
      role: 'ai',
      content: 'Delegating subtask to subagent for processing.',
      runId: RUN_ID_B,
    },
    requestTokenUsage: {
      inputTokens: 180,
      outputTokens: 70,
      totalTokens: 250,
      totalPrice: 0.02,
    },
  },
  {
    id: 'b-msg-2',
    threadId: 'thread-b',
    nodeId: 'node-b-sub',
    externalThreadId: 'ext-thread-b-sub',
    createdAt: '2024-01-01T11:00:01.000Z',
    updatedAt: '2024-01-01T11:00:01.000Z',
    message: {
      role: 'ai',
      content: 'Subagent step 1: retrieving context.',
      runId: RUN_ID_B,
      // totalPrice: number | null until Wave 3 regen widens the autogenerated type
      additionalKwargs: { __hideForLlm: true },
    },
    requestTokenUsage: {
      inputTokens: 90,
      outputTokens: 35,
      totalTokens: 125,
      totalPrice: null,
    },
  },
  {
    id: 'b-msg-3',
    threadId: 'thread-b',
    nodeId: 'node-b-sub',
    externalThreadId: 'ext-thread-b-sub',
    createdAt: '2024-01-01T11:00:02.000Z',
    updatedAt: '2024-01-01T11:00:02.000Z',
    message: {
      role: 'ai',
      content: 'Subagent step 2: processing retrieved data.',
      runId: RUN_ID_B,
      additionalKwargs: { __hideForLlm: true },
    },
    requestTokenUsage: {
      inputTokens: 110,
      outputTokens: 50,
      totalTokens: 160,
      totalPrice: null,
    },
  },
  {
    id: 'b-msg-4',
    threadId: 'thread-b',
    nodeId: 'node-b-sub',
    externalThreadId: 'ext-thread-b-sub',
    createdAt: '2024-01-01T11:00:03.000Z',
    updatedAt: '2024-01-01T11:00:03.000Z',
    message: {
      role: 'ai',
      content: 'Subagent step 3: finalizing output.',
      runId: RUN_ID_B,
      additionalKwargs: { __hideForLlm: true },
    },
    requestTokenUsage: {
      inputTokens: 130,
      outputTokens: 55,
      totalTokens: 185,
      totalPrice: null,
    },
  },
  {
    id: 'b-msg-5',
    threadId: 'thread-b',
    nodeId: 'node-b-outer',
    externalThreadId: 'ext-thread-b',
    createdAt: '2024-01-01T11:00:04.000Z',
    updatedAt: '2024-01-01T11:00:04.000Z',
    message: {
      role: 'ai',
      content: 'Subagent completed. Aggregating results for final response.',
      runId: RUN_ID_B,
    },
    requestTokenUsage: {
      inputTokens: 280,
      outputTokens: 110,
      totalTokens: 390,
      totalPrice: 0.03,
    },
  },
];

// ---------------------------------------------------------------------------
// Scenario C — "All unpriced"
// 4 AI messages, all totalPrice: null.
// Known cost sum = $0. hasUnpricedCalls = true.
// ---------------------------------------------------------------------------

export const scenarioCFixtures: FixtureMessage[] = [
  {
    id: 'c-msg-1',
    threadId: 'thread-c',
    nodeId: 'node-c',
    externalThreadId: 'ext-thread-c',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    message: {
      role: 'ai',
      content: 'Processing request with local model.',
      runId: RUN_ID_C,
    },
    requestTokenUsage: {
      inputTokens: 80,
      outputTokens: 30,
      totalTokens: 110,
      totalPrice: null,
    },
  },
  {
    id: 'c-msg-2',
    threadId: 'thread-c',
    nodeId: 'node-c',
    externalThreadId: 'ext-thread-c',
    createdAt: '2024-01-01T12:00:01.000Z',
    updatedAt: '2024-01-01T12:00:01.000Z',
    message: {
      role: 'ai',
      content: 'Intermediate reasoning step with no pricing data available.',
      runId: RUN_ID_C,
    },
    requestTokenUsage: {
      inputTokens: 150,
      outputTokens: 60,
      totalTokens: 210,
      totalPrice: null,
    },
  },
  {
    id: 'c-msg-3',
    threadId: 'thread-c',
    nodeId: 'node-c',
    externalThreadId: 'ext-thread-c',
    createdAt: '2024-01-01T12:00:02.000Z',
    updatedAt: '2024-01-01T12:00:02.000Z',
    message: {
      role: 'ai',
      content: 'Continuing without cost tracking due to model configuration.',
      runId: RUN_ID_C,
    },
    requestTokenUsage: {
      inputTokens: 200,
      outputTokens: 75,
      totalTokens: 275,
      totalPrice: null,
    },
  },
  {
    id: 'c-msg-4',
    threadId: 'thread-c',
    nodeId: 'node-c',
    externalThreadId: 'ext-thread-c',
    createdAt: '2024-01-01T12:00:03.000Z',
    updatedAt: '2024-01-01T12:00:03.000Z',
    message: {
      role: 'ai',
      content: 'Task complete. Note: cost data unavailable for this run.',
      runId: RUN_ID_C,
    },
    requestTokenUsage: {
      inputTokens: 120,
      outputTokens: 45,
      totalTokens: 165,
      totalPrice: null,
    },
  },
];
