import { useCallback, useEffect, useRef, useState } from 'react';

import type { ThreadMessageDto } from '../../../autogenerated/api';

export interface UseFakeMessageStreamResult {
  messages: ThreadMessageDto[];
  running: boolean;
  restart: () => void;
  stop: () => void;
}

/**
 * Playback hook for storybook cost scenarios.
 *
 * Emits one fixture message per `delayMs` interval, accumulating them in
 * `messages`. Useful for exercising `ThreadMessagesView` + `useChatsUsageStats`
 * in isolation without a live backend.
 *
 * @param fixture - Ordered list of messages to stream.
 * @param delayMs - Milliseconds between each emitted message. Default 300.
 */
export function useFakeMessageStream(
  fixture: ThreadMessageDto[],
  delayMs: number = 300,
): UseFakeMessageStreamResult {
  const [messages, setMessages] = useState<ThreadMessageDto[]>([]);
  const [running, setRunning] = useState<boolean>(true);

  // Use refs for values needed inside the interval callback to avoid stale
  // closures without re-creating the interval on every render.
  const indexRef = useRef<number>(0);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const fixtureRef = useRef<ThreadMessageDto[]>(fixture);

  // Keep fixtureRef current if caller swaps the fixture array.
  useEffect(() => {
    fixtureRef.current = fixture;
  }, [fixture]);

  const clearCurrentInterval = useCallback(() => {
    if (intervalRef.current !== null) {
      clearInterval(intervalRef.current);
      intervalRef.current = null;
    }
  }, []);

  const startInterval = useCallback(() => {
    clearCurrentInterval();
    setRunning(true);

    intervalRef.current = setInterval(() => {
      const currentIndex = indexRef.current;
      const currentFixture = fixtureRef.current;

      if (currentIndex >= currentFixture.length) {
        clearCurrentInterval();
        setRunning(false);
        return;
      }

      setMessages((prev) => [...prev, currentFixture[currentIndex]]);
      indexRef.current = currentIndex + 1;
    }, delayMs);
  }, [clearCurrentInterval, delayMs]);

  // Start on mount.
  useEffect(() => {
    indexRef.current = 0;
    setMessages([]);
    startInterval();

    return clearCurrentInterval;

    // Intentionally not re-running when delayMs changes mid-playback;
    // restart() is the user-facing control for that.
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const restart = useCallback(() => {
    indexRef.current = 0;
    setMessages([]);
    startInterval();
  }, [startInterval]);

  const stop = useCallback(() => {
    clearCurrentInterval();
    setRunning(false);
  }, [clearCurrentInterval]);

  return { messages, running, restart, stop };
}

/**
 * Internals exposed for unit testing only. Not part of the public API.
 * Import as: `import { testInternals } from './useFakeMessageStream'`.
 */
export const testInternals = {
  /** Compute expected total price from a fixture array. */
  sumKnownPrice: (
    fixtures: {
      requestTokenUsage?: { totalPrice?: number } | null;
    }[],
  ): number =>
    fixtures.reduce<number>((acc, msg) => {
      return acc + (msg.requestTokenUsage?.totalPrice ?? 0);
    }, 0),
};
