import { describe, expect, it } from 'vitest';

import type { ThreadMessageDto } from '../autogenerated';
import type {
  ReasoningChunkEntry,
  ReasoningUpsertContext,
} from './threadMessages';
import {
  mergeMessagesReplacingStreaming,
  STREAMING_REASONING_FLAG,
  upsertReasoningEntries,
} from './threadMessages';

// ── Factory helpers ───────────────────────────────────────────────────────────

const makeStreamingReasoningMsg = (
  reasoningId: string,
  overrides: {
    toolCallId?: string;
    subagentCommunication?: boolean;
    interAgentCommunication?: boolean;
    sourceAgentNodeId?: string;
    runId?: string;
  } = {},
): ThreadMessageDto => {
  const kwargs: Record<string, unknown> = {
    __reasoningId: reasoningId,
    [STREAMING_REASONING_FLAG]: true,
  };
  if (overrides.toolCallId) {
    kwargs.__toolCallId = overrides.toolCallId;
  }
  if (overrides.subagentCommunication) {
    kwargs.__subagentCommunication = true;
  }
  if (overrides.interAgentCommunication) {
    kwargs.__interAgentCommunication = true;
  }
  if (overrides.sourceAgentNodeId) {
    kwargs.__sourceAgentNodeId = overrides.sourceAgentNodeId;
  }
  if (overrides.runId) {
    kwargs.__runId = overrides.runId;
  }
  return {
    id: reasoningId,
    threadId: 'thread-1',
    nodeId: reasoningId,
    externalThreadId: '',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    message: {
      id: reasoningId,
      role: 'reasoning' as string,
      content: 'thinking...',
      additionalKwargs: kwargs,
    } as ThreadMessageDto['message'],
  };
};

const makePersistedReasoningMsg = (
  reasoningId: string,
  overrides: {
    toolCallId?: string;
    interAgentCommunication?: boolean;
    runId?: string;
  } = {},
): ThreadMessageDto => {
  const kwargs: Record<string, unknown> = {
    __reasoningId: reasoningId,
    // No STREAMING_REASONING_FLAG — this is a persisted (non-streaming) message
  };
  if (overrides.toolCallId) {
    kwargs.__toolCallId = overrides.toolCallId;
  }
  if (overrides.interAgentCommunication) {
    kwargs.__interAgentCommunication = true;
  }
  if (overrides.runId) {
    kwargs.__runId = overrides.runId;
  }
  return {
    id: `persisted-${reasoningId}`,
    threadId: 'thread-1',
    nodeId: reasoningId,
    externalThreadId: '',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:01:00.000Z',
    message: {
      id: reasoningId,
      role: 'reasoning' as string,
      content: 'full reasoning content',
      additionalKwargs: kwargs,
    } as ThreadMessageDto['message'],
  };
};

const makeEntry = (
  reasoningId: string,
  overrides: Partial<ReasoningChunkEntry> = {},
): ReasoningChunkEntry => ({
  reasoningId,
  content: 'some thinking content',
  ...overrides,
});

const makeContext = (
  overrides: Partial<ReasoningUpsertContext> = {},
): ReasoningUpsertContext => ({
  selectedThreadId: 'thread-1',
  nodeId: 'node-1',
  ...overrides,
});

const getAdditionalKwargs = (msg: ThreadMessageDto): Record<string, unknown> =>
  (msg.message?.additionalKwargs as Record<string, unknown> | undefined) ?? {};

// ── upsertReasoningEntries ────────────────────────────────────────────────────

describe('upsertReasoningEntries', () => {
  it('produces additionalKwargs.__toolCallId from the entry toolCallId', () => {
    const entry = makeEntry('reasoning:abc', { toolCallId: 'tc-1' });
    const result = upsertReasoningEntries([], [entry], makeContext());

    expect(result).toHaveLength(1);
    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__toolCallId).toBe('tc-1');
  });

  it('produces additionalKwargs.__interAgentCommunication from the entry flag', () => {
    const entry = makeEntry('reasoning:abc', {
      toolCallId: 'tc-1',
      interAgentCommunication: true,
    });
    const result = upsertReasoningEntries([], [entry], makeContext());

    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__interAgentCommunication).toBe(true);
  });

  it('produces additionalKwargs.__subagentCommunication from the entry flag', () => {
    const entry = makeEntry('reasoning:abc', {
      subagentCommunication: true,
    });
    const result = upsertReasoningEntries([], [entry], makeContext());

    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__subagentCommunication).toBe(true);
  });

  it('entry toolCallId wins over context toolCallId', () => {
    const entry = makeEntry('reasoning:abc', { toolCallId: 'entry-tc' });
    const ctx = makeContext({ toolCallId: 'context-tc' });
    const result = upsertReasoningEntries([], [entry], ctx);

    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__toolCallId).toBe('entry-tc');
  });

  it('falls back to context toolCallId when entry has none', () => {
    const entry = makeEntry('reasoning:abc');
    const ctx = makeContext({ toolCallId: 'context-tc' });
    const result = upsertReasoningEntries([], [entry], ctx);

    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__toolCallId).toBe('context-tc');
  });

  it('does NOT set __toolCallId when neither entry nor context provides one', () => {
    const entry = makeEntry('reasoning:abc');
    const ctx = makeContext();
    const result = upsertReasoningEntries([], [entry], ctx);

    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__toolCallId).toBeUndefined();
  });

  it('does NOT set __interAgentCommunication when the entry flag is absent', () => {
    const entry = makeEntry('reasoning:abc', { toolCallId: 'tc-1' });
    const result = upsertReasoningEntries([], [entry], makeContext());

    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__interAgentCommunication).toBeUndefined();
  });

  it('sets the STREAMING_REASONING_FLAG on the produced message', () => {
    const entry = makeEntry('reasoning:abc');
    const result = upsertReasoningEntries([], [entry], makeContext());

    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs[STREAMING_REASONING_FLAG]).toBe(true);
  });

  it('entry toolCallId + interAgentCommunication are both set together', () => {
    const entry = makeEntry('reasoning:abc', {
      toolCallId: 'tc-1',
      interAgentCommunication: true,
    });
    const result = upsertReasoningEntries([], [entry], makeContext());

    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__toolCallId).toBe('tc-1');
    expect(kwargs.__interAgentCommunication).toBe(true);
  });

  it('sourceAgentNodeId is forwarded from the entry', () => {
    const entry = makeEntry('reasoning:abc', {
      toolCallId: 'tc-1',
      sourceAgentNodeId: 'agent-node-x',
    });
    const result = upsertReasoningEntries([], [entry], makeContext());

    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__sourceAgentNodeId).toBe('agent-node-x');
  });
});

// ── mergeMessagesReplacingStreaming ───────────────────────────────────────────

describe('mergeMessagesReplacingStreaming', () => {
  it('carries __toolCallId forward from the outgoing streaming entry to the persisted reasoning message when the persisted message lacks it', () => {
    // The streaming entry carries __toolCallId but the backend-persisted message
    // does not (simulating backend tagging drift / defensive carry-forward).
    const streamingMsg = makeStreamingReasoningMsg('reasoning:abc', {
      toolCallId: 'tc-1',
    });
    // The persisted message uses the same reasoning id so it replaces the streaming one.
    const persistedMsg = makePersistedReasoningMsg('reasoning:abc');

    const result = mergeMessagesReplacingStreaming(
      [streamingMsg],
      [persistedMsg],
    );

    // The streaming entry should be gone; the persisted entry should have
    // inherited __toolCallId from the streaming entry.
    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__toolCallId).toBe('tc-1');
    // The STREAMING_REASONING_FLAG must NOT be set on the persisted message.
    expect(kwargs[STREAMING_REASONING_FLAG]).toBeFalsy();
  });

  it('carries __interAgentCommunication forward from the outgoing streaming entry', () => {
    const streamingMsg = makeStreamingReasoningMsg('reasoning:abc', {
      toolCallId: 'tc-1',
      interAgentCommunication: true,
    });
    const persistedMsg = makePersistedReasoningMsg('reasoning:abc');

    const result = mergeMessagesReplacingStreaming(
      [streamingMsg],
      [persistedMsg],
    );

    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__interAgentCommunication).toBe(true);
  });

  it('does NOT synthesize __toolCallId when neither the streaming entry nor the persisted message has one', () => {
    // Negative case: no toolCallId anywhere — must not be invented.
    const streamingMsg = makeStreamingReasoningMsg('reasoning:abc');
    const persistedMsg = makePersistedReasoningMsg('reasoning:abc');

    const result = mergeMessagesReplacingStreaming(
      [streamingMsg],
      [persistedMsg],
    );

    const kwargs = getAdditionalKwargs(result[0]);
    expect(kwargs.__toolCallId).toBeUndefined();
  });

  it('keeps __toolCallId from the persisted message when it is already tagged', () => {
    // When the persisted message already carries __toolCallId, that value wins
    // (no need to carry-forward from the streaming entry).
    const streamingMsg = makeStreamingReasoningMsg('reasoning:abc', {
      toolCallId: 'tc-streaming',
    });
    const persistedMsg = makePersistedReasoningMsg('reasoning:abc', {
      toolCallId: 'tc-persisted',
    });

    const result = mergeMessagesReplacingStreaming(
      [streamingMsg],
      [persistedMsg],
    );

    const kwargs = getAdditionalKwargs(result[0]);
    // Already-tagged persisted message is inserted as-is.
    expect(kwargs.__toolCallId).toBe('tc-persisted');
  });

  it('matches by run id when reasoning ids differ and carries __toolCallId forward', () => {
    // Streaming entry and persisted message share the same runId but different
    // message ids — still triggers carry-forward.
    const streamingMsg = makeStreamingReasoningMsg('reasoning:stream-id', {
      toolCallId: 'tc-run',
      runId: 'run-xyz',
    });
    const persistedMsg = makePersistedReasoningMsg('reasoning:other-id', {
      runId: 'run-xyz',
    });

    const result = mergeMessagesReplacingStreaming(
      [streamingMsg],
      [persistedMsg],
    );

    const persistedInResult = result.find(
      (m) => m.id === `persisted-reasoning:other-id`,
    );
    if (!persistedInResult) {
      throw new Error('persisted message not found in result');
    }
    const kwargs = getAdditionalKwargs(persistedInResult);
    expect(kwargs.__toolCallId).toBe('tc-run');
  });

  it('does not carry __toolCallId forward when the streaming entry carries no comm-routing kwargs', () => {
    // If the streaming entry has no comm-routing kwargs at all, carry-forward
    // must be a no-op — do not produce undefined-valued keys.
    const streamingMsg = makeStreamingReasoningMsg('reasoning:plain');
    const persistedMsg = makePersistedReasoningMsg('reasoning:plain');

    const result = mergeMessagesReplacingStreaming(
      [streamingMsg],
      [persistedMsg],
    );

    const kwargs = getAdditionalKwargs(result[0]);
    expect(Object.keys(kwargs)).not.toContain('__toolCallId');
    expect(Object.keys(kwargs)).not.toContain('__interAgentCommunication');
    expect(Object.keys(kwargs)).not.toContain('__subagentCommunication');
  });
});
