// @vitest-environment jsdom
import { act, renderHook, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// ── Module mocks ──────────────────────────────────────────────────────────────

// Mock the API module — controls the apiTotal side of the hook.
vi.mock('../../../api', () => ({
  threadsApi: {
    getThreadUsageStatistics: vi.fn(),
  },
}));

// ── Imports after mocks ───────────────────────────────────────────────────────

import { threadsApi } from '../../../api';
import type { ThreadDto } from '../../../autogenerated';
import type { ThreadTokenUsageSnapshot } from '../types';
import { useChatsUsageStats } from './useChatsUsageStats';

// ── Helpers ───────────────────────────────────────────────────────────────────

const toastMessage = {
  success: vi.fn(),
  error: vi.fn(),
  warning: vi.fn(),
  info: vi.fn(),
  loading: vi.fn(),
  open: vi.fn(),
  destroy: vi.fn(),
};

const makeThread = (overrides: Partial<ThreadDto> = {}): ThreadDto =>
  ({
    id: 'thread-1',
    graphId: 'graph-1',
    status: 'running',
    effectiveCostLimitUsd: null,
    name: 'Test thread',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...overrides,
  }) as unknown as ThreadDto;

const makeUsageStats = (total: Partial<ThreadTokenUsageSnapshot>) => ({
  data: {
    total: {
      inputTokens: 0,
      cachedInputTokens: 0,
      outputTokens: 0,
      reasoningTokens: 0,
      totalTokens: 0,
      totalPrice: 0,
      currentContext: 0,
      ...total,
    },
    byNode: {
      'node-1': {
        inputTokens: total.inputTokens ?? 0,
        cachedInputTokens: total.cachedInputTokens ?? 0,
        outputTokens: total.outputTokens ?? 0,
        reasoningTokens: total.reasoningTokens ?? 0,
        totalTokens: total.totalTokens ?? 0,
        totalPrice: total.totalPrice ?? 0,
        currentContext: total.currentContext ?? 0,
      },
    },
  },
});

const makeAggregateByNode = (
  snap: Partial<ThreadTokenUsageSnapshot>,
): Record<string, Record<string, ThreadTokenUsageSnapshot>> => ({
  'thread-1': {
    'node-1': {
      inputTokens: snap.inputTokens ?? 0,
      cachedInputTokens: snap.cachedInputTokens ?? 0,
      outputTokens: snap.outputTokens ?? 0,
      reasoningTokens: snap.reasoningTokens ?? 0,
      totalTokens: snap.totalTokens ?? 0,
      totalPrice: snap.totalPrice ?? 0,
      currentContext: snap.currentContext ?? 0,
    },
  },
});

// ── Shared teardown ───────────────────────────────────────────────────────────

afterEach(() => {
  vi.clearAllMocks();
});

// ── Tests ─────────────────────────────────────────────────────────────────────

describe('useChatsUsageStats — selectedThreadThreadUsage', () => {
  beforeEach(() => {
    // Default: API returns zero stats so tests that set aggregate can compare clearly.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0, totalTokens: 0 }));
  });

  it('returns Math.max per additive field when Running and apiTotal > aggregate', async () => {
    // apiTotal has higher totalPrice than aggregate
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(
      makeUsageStats({
        inputTokens: 200,
        outputTokens: 100,
        totalTokens: 300,
        totalPrice: 0.3,
        currentContext: 5000,
      }),
    );

    const selectedThread = makeThread({ status: 'running' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Set aggregate with lower values than apiTotal
    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({
          inputTokens: 100,
          outputTokens: 50,
          totalTokens: 150,
          totalPrice: 0.1,
          currentContext: 3000,
        }),
      );
    });

    // Wait for API fetch to complete (hook auto-loads on mount)
    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage?.totalPrice).toBe(0.3);
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.inputTokens).toBe(200);
    expect(usage?.outputTokens).toBe(100);
    expect(usage?.totalTokens).toBe(300);
    expect(usage?.totalPrice).toBe(0.3);
    // currentContext is a snapshot (not additive) — taken from aggregate, not Math.max-ed
    expect(usage?.currentContext).toBe(3000);
  });

  it('returns aggregate fields when Running and aggregate > apiTotal', async () => {
    // apiTotal has lower totalPrice than aggregate
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(
      makeUsageStats({
        inputTokens: 50,
        outputTokens: 25,
        totalTokens: 75,
        totalPrice: 0.05,
        currentContext: 1000,
      }),
    );

    const selectedThread = makeThread({ status: 'running' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Set aggregate with higher values than apiTotal
    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({
          inputTokens: 300,
          outputTokens: 200,
          totalTokens: 500,
          totalPrice: 0.5,
          currentContext: 8000,
        }),
      );
    });

    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage?.totalPrice).toBe(0.5);
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.inputTokens).toBe(300);
    expect(usage?.outputTokens).toBe(200);
    expect(usage?.totalTokens).toBe(500);
    expect(usage?.totalPrice).toBe(0.5);
    // currentContext is a snapshot (not additive) — taken from aggregate, not Math.max-ed
    expect(usage?.currentContext).toBe(8000);
  });

  it('returns apiTotal when thread is Stopped', async () => {
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(
      makeUsageStats({
        inputTokens: 400,
        outputTokens: 250,
        totalTokens: 650,
        totalPrice: 0.42,
        currentContext: 6000,
      }),
    );

    const selectedThread = makeThread({ status: 'stopped' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Aggregate also has data — stopped thread must prefer apiTotal
    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({
          inputTokens: 100,
          totalPrice: 0.1,
        }),
      );
    });

    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage?.totalPrice).toBe(0.42);
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.inputTokens).toBe(400);
    expect(usage?.outputTokens).toBe(250);
    expect(usage?.totalTokens).toBe(650);
    expect(usage?.totalPrice).toBe(0.42);
  });

  it('includes effectiveCostLimitUsd from selectedThread', async () => {
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0.1 }));

    const selectedThread = makeThread({
      status: 'running',
      effectiveCostLimitUsd: 5,
    });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({ totalPrice: 0.1 }),
      );
    });

    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage).toBeDefined();
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.effectiveCostLimitUsd).toBe(5);
  });
});
