// @vitest-environment jsdom
import { act, renderHook, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// ── Module mocks ──────────────────────────────────────────────────────────────

// Mock the API module — controls the apiTotal side of the hook.
vi.mock('../../../api', () => ({
  threadsApi: {
    getThreadUsageStatistics: vi.fn(),
  },
}));

// ── Imports after mocks ───────────────────────────────────────────────────────

import { threadsApi } from '../../../api';
import type { ThreadDto } from '../../../autogenerated';
import type { ThreadTokenUsageSnapshot } from '../types';
import { useChatsUsageStats } from './useChatsUsageStats';

// ── Helpers ───────────────────────────────────────────────────────────────────

const toastMessage = {
  success: vi.fn(),
  error: vi.fn(),
  warning: vi.fn(),
  info: vi.fn(),
  loading: vi.fn(),
  open: vi.fn(),
  destroy: vi.fn(),
};

const makeThread = (overrides: Partial<ThreadDto> = {}): ThreadDto =>
  ({
    id: 'thread-1',
    graphId: 'graph-1',
    status: 'running',
    effectiveCostLimitUsd: null,
    name: 'Test thread',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...overrides,
  }) as unknown as ThreadDto;

const makeUsageStats = (total: Partial<ThreadTokenUsageSnapshot>) => ({
  data: {
    total: {
      inputTokens: 0,
      cachedInputTokens: 0,
      outputTokens: 0,
      reasoningTokens: 0,
      totalTokens: 0,
      totalPrice: 0,
      currentContext: 0,
      ...total,
    },
    byNode: {
      'node-1': {
        inputTokens: total.inputTokens ?? 0,
        cachedInputTokens: total.cachedInputTokens ?? 0,
        outputTokens: total.outputTokens ?? 0,
        reasoningTokens: total.reasoningTokens ?? 0,
        totalTokens: total.totalTokens ?? 0,
        totalPrice: total.totalPrice,
        currentContext: total.currentContext ?? 0,
      },
    },
  },
});

const makeAggregateByNode = (
  snap: Partial<ThreadTokenUsageSnapshot>,
): Record<string, Record<string, ThreadTokenUsageSnapshot>> => ({
  'thread-1': {
    'node-1': {
      inputTokens: snap.inputTokens ?? 0,
      cachedInputTokens: snap.cachedInputTokens ?? 0,
      outputTokens: snap.outputTokens ?? 0,
      reasoningTokens: snap.reasoningTokens ?? 0,
      totalTokens: snap.totalTokens ?? 0,
      totalPrice: snap.totalPrice,
      currentContext: snap.currentContext ?? 0,
    },
  },
});

// ── Shared teardown ───────────────────────────────────────────────────────────

afterEach(() => {
  vi.clearAllMocks();
});

// ── Tests ─────────────────────────────────────────────────────────────────────

describe('useChatsUsageStats — selectedThreadThreadUsage', () => {
  beforeEach(() => {
    // Default: API returns zero stats so tests that set aggregate can compare clearly.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0, totalTokens: 0 }));
  });

  it('returns aggregate fields when Running regardless of apiTotal magnitude (single-source policy)', async () => {
    // apiTotal has higher totalPrice than aggregate — but single-source policy means aggregate wins
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(
      makeUsageStats({
        inputTokens: 200,
        outputTokens: 100,
        totalTokens: 300,
        totalPrice: 0.3,
        currentContext: 5000,
      }),
    );

    const selectedThread = makeThread({ status: 'running' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Set aggregate with lower values than apiTotal
    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({
          inputTokens: 100,
          outputTokens: 50,
          totalTokens: 150,
          totalPrice: 0.1,
          currentContext: 3000,
        }),
      );
    });

    // Wait for API fetch to complete (hook auto-loads on mount), then verify aggregate wins
    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage?.totalPrice).toBe(0.1);
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.inputTokens).toBe(100);
    expect(usage?.outputTokens).toBe(50);
    expect(usage?.totalTokens).toBe(150);
    expect(usage?.totalPrice).toBe(0.1);
    // Single-source policy: while running, aggregate wins for all fields including currentContext
    expect(usage?.currentContext).toBe(3000);
    // Scenario 1 (matrix row 1 — all priced, running): hasUnpricedCalls must be false.
    expect(result.current.selectedThreadThreadUsage?.hasUnpricedCalls).toBe(
      false,
    );
  });

  it('returns aggregate fields when Running (single-source policy)', async () => {
    // apiTotal has lower totalPrice than aggregate
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(
      makeUsageStats({
        inputTokens: 50,
        outputTokens: 25,
        totalTokens: 75,
        totalPrice: 0.05,
        currentContext: 1000,
      }),
    );

    const selectedThread = makeThread({ status: 'running' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Set aggregate with higher values than apiTotal
    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({
          inputTokens: 300,
          outputTokens: 200,
          totalTokens: 500,
          totalPrice: 0.5,
          currentContext: 8000,
        }),
      );
    });

    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage?.totalPrice).toBe(0.5);
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.inputTokens).toBe(300);
    expect(usage?.outputTokens).toBe(200);
    expect(usage?.totalTokens).toBe(500);
    expect(usage?.totalPrice).toBe(0.5);
    // Single-source policy: while running, aggregate wins for all fields including currentContext
    expect(usage?.currentContext).toBe(8000);
  });

  it('returns apiTotal when thread is Stopped', async () => {
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(
      makeUsageStats({
        inputTokens: 400,
        outputTokens: 250,
        totalTokens: 650,
        totalPrice: 0.42,
        currentContext: 6000,
      }),
    );

    const selectedThread = makeThread({ status: 'stopped' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Aggregate also has data — stopped thread must prefer apiTotal
    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({
          inputTokens: 100,
          totalPrice: 0.1,
        }),
      );
    });

    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage?.totalPrice).toBe(0.42);
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.inputTokens).toBe(400);
    expect(usage?.outputTokens).toBe(250);
    expect(usage?.totalTokens).toBe(650);
    expect(usage?.totalPrice).toBe(0.42);
    // Scenario 2 (matrix row 2 — all priced, done): hasUnpricedCalls must be false.
    expect(result.current.selectedThreadThreadUsage?.hasUnpricedCalls).toBe(
      false,
    );
  });

  it('includes effectiveCostLimitUsd from selectedThread', async () => {
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0.1 }));

    const selectedThread = makeThread({
      status: 'running',
      effectiveCostLimitUsd: 5,
    });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({ totalPrice: 0.1 }),
      );
    });

    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage).toBeDefined();
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.effectiveCostLimitUsd).toBe(5);
  });

  // Scenario 3.3: Running + aggregate.totalPrice > apiTotal.totalPrice → hook returns withLimit(aggregate).
  // Covered by 'returns aggregate fields when Running (single-source policy)' above — that test
  // explicitly sets aggregate higher than apiTotal and asserts field-for-field equality with aggregate.

  // Scenario 3.4: running→done transition triggers exactly one fetch; extra re-render without
  // status change must NOT fire another fetch (StrictMode / redundant render safety).
  // Scenario 6 (matrix row 6 — running→done with fresh REST fetch returning hasUnpricedCalls: true):
  // The transition fetch mock carries hasUnpricedCalls: true. After transition the hook must expose it.
  // RED until Wave 4: apiTotal shape does not include hasUnpricedCalls, so the hook cannot propagate it.
  it('fetches once on running→done transition and not again on a redundant re-render (3.4)', async () => {
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0.2 }));

    const runningThread = makeThread({ status: 'running' });
    const doneThread = makeThread({ status: 'done' });

    const { result, rerender } = renderHook(
      (props: { thread: typeof runningThread }) =>
        useChatsUsageStats({
          toastMessage,
          selectedThread: props.thread,
          selectedThreadId: 'thread-1',
          selectedThreadIsDraft: false,
          selectedAgentNodeId: null,
          graphCache: {},
          getFullGraph: () => undefined,
        }),
      { initialProps: { thread: runningThread } },
    );

    // Let the mount-fetch settle so its call is counted.
    await waitFor(() => {
      expect(
        threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>,
      ).toHaveBeenCalled();
    });

    // Reset mock call count so we isolate transition-triggered fetches.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockClear();

    // Transition: running → done — must trigger exactly one fetch.
    rerender({ thread: doneThread });

    await waitFor(() => {
      expect(
        threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>,
      ).toHaveBeenCalledTimes(1);
    });

    expect(
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>,
    ).toHaveBeenCalledWith('thread-1');

    // Scenario 6: re-mock with hasUnpricedCalls: true, then do a fresh running→done
    // transition so the transition effect fires with the new mock. The hook must expose
    // hasUnpricedCalls: true directly from the REST response — no secondary fetch needed.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue({
      data: {
        total: {
          inputTokens: 200,
          cachedInputTokens: 0,
          outputTokens: 100,
          reasoningTokens: 0,
          totalTokens: 300,
          totalPrice: null,
          currentContext: 0,
          hasUnpricedCalls: true,
        },
        byNode: {},
      },
    });

    // Go back to running so the next rerender produces a clean running→done transition.
    rerender({ thread: runningThread });
    // Now transition to done — this fires the transition effect with the new mock.
    rerender({ thread: doneThread });

    await waitFor(() => {
      expect(result.current.selectedThreadThreadUsage?.hasUnpricedCalls).toBe(
        true,
      );
    });

    // totalPrice null must survive — not coerced to 0.
    // RED: current hook reads usageStats.total.totalPrice which is typed as number|undefined;
    // null passes through JS but the type does not reflect it yet.
    expect(result.current.selectedThreadThreadUsage?.totalPrice).toBeNull();

    // Reset again to verify redundant re-render (same status) does NOT fire another fetch.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockClear();

    // Re-render with same done status — must NOT fire fetch.
    // Use fake timers so the assertion is deterministic regardless of CI load (H4 fix).
    vi.useFakeTimers();
    rerender({ thread: makeThread({ status: 'done' }) });
    vi.runAllTimers();
    await Promise.resolve(); // flush microtasks
    vi.useRealTimers();

    expect(
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>,
    ).not.toHaveBeenCalled();
  });

  it('does not fetch when switching from a running thread to a different thread that is already done', async () => {
    // Pre-populate stats for thread B so the mount-effect short-circuits and
    // does not call getThreadUsageStatistics at all, leaving only the transition
    // effect to potentially trigger a fetch.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0.1 }));

    const threadA = makeThread({ id: 'a', status: 'running' });
    const threadB = makeThread({ id: 'b', status: 'done' });

    const { rerender, result } = renderHook(
      (props: { thread: typeof threadA; threadId: string }) =>
        useChatsUsageStats({
          toastMessage,
          selectedThread: props.thread,
          selectedThreadId: props.threadId,
          selectedThreadIsDraft: false,
          selectedAgentNodeId: null,
          graphCache: {},
          getFullGraph: () => undefined,
        }),
      { initialProps: { thread: threadA, threadId: 'a' } },
    );

    // Let mount-effect for thread A settle.
    await waitFor(() => {
      expect(
        threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>,
      ).toHaveBeenCalledWith('a');
    });

    // Reset so we can assert cleanly on thread B calls only.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockClear();

    // Switch to thread B (different id, already done — never ran→done on its own).
    // The transition effect must NOT fire a fetch for B because B's identity changed,
    // not because B transitioned from running.
    vi.useFakeTimers();
    rerender({ thread: threadB, threadId: 'b' });
    vi.runAllTimers();
    await Promise.resolve(); // flush microtasks
    vi.useRealTimers();

    // The transition effect must not have fired for thread B.
    // (The mount effect may call once for B if stats are missing — that is acceptable,
    // but we assert the count is at most 1, not 2, ruling out a double fetch.)
    const callsForB = (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mock.calls.filter((args: unknown[]) => args[0] === 'b');
    expect(callsForB.length).toBeLessThanOrEqual(1);

    // Row 7 (thread-switch during running): after switching to thread B the hook
    // must not display thread A's stale stats for thread B.
    // The mock resolves with totalPrice: 0.1 for any threadId. If a fetch occurred for
    // thread B, selectedThreadThreadUsage.totalPrice must be 0.1 (not stale thread A data).
    // Allow time for any pending fetch and state update to settle.
    await waitFor(() => {
      expect(result.current.selectedThreadThreadUsage).toBeDefined();
      expect(result.current.selectedThreadThreadUsage?.totalPrice).toBeCloseTo(
        0.1,
        5,
      );
    });
  });

  // Scenario 4-web (matrix row 4 — all calls unpriced, thread done):
  // REST snapshot returns totalPrice: null + hasUnpricedCalls: true.
  // Hook must propagate totalPrice === null (not coerce to 0) and surface hasUnpricedCalls: true.
  // RED: ThreadTokenUsageSnapshot.totalPrice is typed as number | undefined; null is not handled.
  // Also RED: hasUnpricedCalls is not on the snapshot type or hook output until Wave 4.
  it('Scenario 4-web: exposes totalPrice===null and hasUnpricedCalls===true when all calls unpriced (RED until Wave 4)', async () => {
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue({
      data: {
        total: {
          inputTokens: 500,
          cachedInputTokens: 0,
          outputTokens: 250,
          reasoningTokens: 0,
          totalTokens: 750,
          totalPrice: null,
          currentContext: 0,
          hasUnpricedCalls: true,
        },
        byNode: {},
      },
    });

    const selectedThread = makeThread({ status: 'done' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    await waitFor(() => {
      expect(result.current.selectedThreadThreadUsage).toBeDefined();
    });

    const usage = result.current.selectedThreadThreadUsage;

    // totalPrice must be null — not coerced to 0 or undefined.
    // RED: hook currently reads `usageStats.total.totalPrice` typed as number|undefined;
    // null passes through JS but will appear as null here, which fails toBeNull when
    // the hook coerces via `?? 0` or similar pattern.
    expect(usage?.totalPrice).toBeNull();

    expect(usage?.hasUnpricedCalls).toBe(true);
  });
});
