// @vitest-environment jsdom
import { act, renderHook } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { ThreadDtoStatusEnum } from '../../../autogenerated/api';
import { useLiveThreadDuration } from './useLiveThreadDuration';

describe('useLiveThreadDuration', () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('frozen mode: returns totalRunningMs when status is stopped', () => {
    const { result } = renderHook(() =>
      useLiveThreadDuration({
        runningStartedAt: null,
        totalRunningMs: 12345,
        status: ThreadDtoStatusEnum.Done,
      }),
    );
    expect(result.current).toBe(12345);

    // Advance time — should remain frozen
    act(() => {
      vi.advanceTimersByTime(5000);
    });
    expect(result.current).toBe(12345);
  });

  it('frozen mode: returns 0 when totalRunningMs is undefined', () => {
    const { result } = renderHook(() =>
      useLiveThreadDuration({
        runningStartedAt: null,
        totalRunningMs: undefined,
        status: ThreadDtoStatusEnum.Done,
      }),
    );
    expect(result.current).toBe(0);
  });

  it('live mode: returns totalRunningMs + elapsed when running', () => {
    const startedAt = new Date(Date.now() - 1000).toISOString();

    const { result } = renderHook(() =>
      useLiveThreadDuration({
        runningStartedAt: startedAt,
        totalRunningMs: 5000,
        status: ThreadDtoStatusEnum.Running,
      }),
    );

    // Initial value: ~6000ms (5000 base + ~1000 elapsed)
    expect(result.current).toBeGreaterThanOrEqual(5900);
    expect(result.current).toBeLessThan(7000);
  });

  it('live mode: ticks every second via interval', () => {
    const startedAt = new Date(Date.now()).toISOString();

    const { result } = renderHook(() =>
      useLiveThreadDuration({
        runningStartedAt: startedAt,
        totalRunningMs: 0,
        status: ThreadDtoStatusEnum.Running,
      }),
    );

    const initial = result.current;

    act(() => {
      vi.advanceTimersByTime(3000);
    });

    expect(result.current).toBeGreaterThan(initial + 2500);
  });

  it('status flip running→done: returns frozen totalRunningMs', () => {
    let status: ThreadDtoStatusEnum = ThreadDtoStatusEnum.Running;
    const startedAt = new Date(Date.now() - 2000).toISOString();

    const { result, rerender } = renderHook(() =>
      useLiveThreadDuration({
        runningStartedAt: startedAt,
        totalRunningMs: 8000,
        status,
      }),
    );

    // Confirm it is live
    expect(result.current).toBeGreaterThan(8000);

    // Flip to done
    status = ThreadDtoStatusEnum.Done;
    rerender();

    const frozenValue = result.current;

    act(() => {
      vi.advanceTimersByTime(5000);
    });

    // Must not increase after status left running
    expect(result.current).toBe(frozenValue);
    expect(result.current).toBe(8000);
  });

  it('waiting→running transition: no negative duration flash on re-entry', () => {
    let status: ThreadDtoStatusEnum = ThreadDtoStatusEnum.Done;
    let runningStartedAt: string | null = null;
    let totalRunningMs = 0;

    const { result, rerender } = renderHook(() =>
      useLiveThreadDuration({
        runningStartedAt,
        totalRunningMs,
        status,
      }),
    );

    expect(result.current).toBe(0);

    // Simulate 5 minutes passing while thread is stopped/waiting
    act(() => {
      vi.advanceTimersByTime(5 * 60 * 1000);
    });

    // Thread re-enters Running with a fresh runningStartedAt = now
    // and some accumulated totalRunningMs from a prior run
    act(() => {
      status = ThreadDtoStatusEnum.Running;
      runningStartedAt = new Date(Date.now()).toISOString();
      totalRunningMs = 10000;
      rerender();
    });

    // Must NOT be negative — the stale nowMs bug would yield a large negative value here
    expect(result.current).toBeGreaterThanOrEqual(10000);
  });

  it('invalid runningStartedAt: gracefully returns totalRunningMs (no NaN)', () => {
    const { result } = renderHook(() =>
      useLiveThreadDuration({
        runningStartedAt: 'not-a-date',
        totalRunningMs: 3000,
        status: ThreadDtoStatusEnum.Running,
      }),
    );

    expect(result.current).toBe(3000);
    expect(Number.isNaN(result.current)).toBe(false);
  });
});
